import { useCallback, useEffect, useMemo, useState } from 'react'
import { HttpError } from '../../../services/http/http-client'
import { canPerformBackendAction } from '../../auth/policies/access-policy'
import { useAuthSession } from '../../auth/context/useAuthSession'
import { getAcademicWorkflowContext } from '../api/academic-api'
import { getProjectPeriods, getSemesters, saveProjectPeriod, saveSemester, setGovernanceStatus } from '../api/governance-api'
import type { GovernanceFilters, ProjectPeriodDraft, SemesterDraft } from '../types/governance.types'
const initial:GovernanceFilters={search:''}
export function useAcademicGovernance(filters:GovernanceFilters=initial) { const {session}=useAuthSession(); const { search, semesterId, status }=filters; const [semesters,setSemesters]=useState([] as Awaited<ReturnType<typeof getSemesters>>['items']); const [periods,setPeriods]=useState([] as Awaited<ReturnType<typeof getProjectPeriods>>['items']); const [context,setContext]=useState<Awaited<ReturnType<typeof getAcademicWorkflowContext>>|null>(null); const [error,setError]=useState<Error|null>(null); const [loading,setLoading]=useState(!!session); const [submitting,setSubmitting]=useState(false); const [version,setVersion]=useState(0); const retry=useCallback(()=>setVersion(v=>v+1),[]);
 useEffect(()=>{if(!session){setLoading(false);return} const c=new AbortController();setLoading(true);setError(null);Promise.all([getSemesters(session.accessToken,{search,status},c.signal),getProjectPeriods(session.accessToken,{search,semesterId,status},c.signal),getAcademicWorkflowContext(session.accessToken,c.signal)]).then(([s,p,ctx])=>{setSemesters(s.items);setPeriods(p.items);setContext(ctx)}).catch(e=>!c.signal.aborted&&setError(e instanceof Error?e:new Error('Load failed'))).finally(()=>!c.signal.aborted&&setLoading(false));return()=>c.abort()},[session,search,semesterId,status,version]);
 const mutate=useCallback(async (operation:()=>Promise<unknown>)=>{setSubmitting(true);try{await operation();retry()}finally{setSubmitting(false)}},[retry]); const canManage=useMemo(()=>canPerformBackendAction(context?.actions??[],'manage_academic_structure'),[context]);
 return {semesters,periods,error,loading,submitting,isForbidden:error instanceof HttpError&&error.status===403,isUnauthorized:!session||(error instanceof HttpError&&error.status===401),canManage,retry,saveSemester:(d:SemesterDraft)=>mutate(()=>saveSemester(d,session!.accessToken)),saveProjectPeriod:(d:ProjectPeriodDraft)=>mutate(()=>saveProjectPeriod(d,session!.accessToken)),setStatus:(k:'semester'|'period',id:number,status:string,expected:string)=>mutate(()=>setGovernanceStatus(k,id,status,expected,session!.accessToken))} }
