import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { HttpError } from '../../../services/http/http-client'
import { getArchiveView } from '../api/archive-project'
import type { ProjectDto, ProjectStatusHistoryDto } from '../../../types/backend'
import { projectStatusLabel } from '../utils/project-status'

export function ProjectArchiveViewPage() {
  const id = Number(useParams().projectId); const [data, setData] = useState<{ project: ProjectDto; history: ProjectStatusHistoryDto[] } | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { if (!Number.isSafeInteger(id) || id < 1) { setError('Đường dẫn đồ án không hợp lệ.'); setLoading(false); return }; setLoading(true); try { const [project, history] = await getArchiveView(id); if (project.status.replaceAll('_', '').toUpperCase() !== 'ARCHIVED') { setError('Đồ án này chưa ở trạng thái ARCHIVED do Backend trả về.'); setData(null) } else { setData({ project, history: [...history].sort((a, b) => Date.parse(b.changedAt) - Date.parse(a.changedAt)) }); setError(null) } } catch (reason) { setError(reason instanceof HttpError && reason.status === 403 ? 'Backend không cấp quyền xem đồ án lưu trữ này.' : reason instanceof HttpError && reason.status === 404 ? 'Không tìm thấy đồ án lưu trữ.' : 'Không thể tải dữ liệu lưu trữ từ Backend.') } finally { setLoading(false) } }, [id])
  useEffect(() => { void load() }, [load])
  return <main className="mx-auto max-w-5xl space-y-5 pb-12"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-xs font-semibold uppercase tracking-wide text-primary">Archive · read only</p><h1 className="mt-1 font-heading text-2xl font-bold text-slate-950">Hồ sơ đồ án lưu trữ</h1><p className="mt-2 text-sm text-slate-600">Trang này không cung cấp bất kỳ thao tác thay đổi nào.</p></div><Link to="/department/projects/archived" className="inline-flex min-h-11 items-center font-semibold text-primary underline underline-offset-4">Kho lưu trữ</Link></header>{loading && <p role="status" className="rounded-xl border border-hairline bg-card p-5 text-sm text-slate-600">Đang tải hồ sơ lưu trữ…</p>}{error && <section role="alert" className="rounded-xl border border-status-error-border bg-status-error-bg p-5 text-sm text-status-error-text"><p>{error}</p><button type="button" className="mt-2 min-h-11 font-semibold underline underline-offset-4" onClick={() => void load()}>Tải lại</button></section>}{data && <><section className="rounded-xl border border-status-success-border bg-status-success-bg p-5"><p className="text-xs font-semibold uppercase tracking-wide text-status-success-text">{projectStatusLabel(data.project.status)}</p><h2 className="mt-1 font-heading text-xl font-bold text-slate-950">{data.project.code} · {data.project.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{data.project.description || 'Backend chưa có mô tả đồ án.'}</p></section><section className="rounded-xl border border-hairline bg-card p-5 shadow-xs"><h2 className="font-heading text-lg font-semibold text-slate-950">Lịch sử trạng thái</h2>{data.history.length ? <ol className="mt-4 divide-y divide-hairline">{data.history.map(item => <li key={item.id} className="py-3 text-sm"><p className="font-semibold text-slate-900">{item.oldStatus ? projectStatusLabel(item.oldStatus) : 'Khởi tạo'} → {projectStatusLabel(item.newStatus)}</p><p className="mt-1 text-slate-600">{item.changedByName || 'Hệ thống'}{item.reason ? ` · ${item.reason}` : ''}</p><time className="mt-1 block text-xs text-slate-500">{new Date(item.changedAt).toLocaleString('vi-VN')}</time></li>)}</ol> : <p className="mt-3 text-sm text-slate-600">Backend chưa trả lịch sử trạng thái.</p>}</section></>}</main>
}
