import { displayLabel } from '../../../components/ui/display-label'
import { ProjectGovernanceEditor } from '../components/ProjectGovernanceEditor'
import { AssignmentManagementPanel } from '../../supervisors/components/AssignmentManagementPanel'
import { WorkspacePage } from '../../../components/ui/WorkspacePage'
import { useCallback, useEffect, useRef, useState } from 'react'
import { useParams } from 'react-router-dom'
import { getMeetings } from '../../../services/api/meetings.api'
import { getProgressReports } from '../../../services/api/progress-reports.api'
import { getProject } from '../../../services/api/projects.api'
import { HttpError } from '../../../services/http/http-client'
import * as api from '../api/project-governance-api'

const date = (value: string | null) => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—'
function errorText(reason: unknown) { if (reason instanceof HttpError) { if (reason.status === 403) return 'Bạn chưa có quyền thao tác trong đồ án này.'; if (reason.status === 409) return 'Dữ liệu vừa thay đổi. Danh sách mới đã được tải lại; hãy kiểm tra trước khi lưu.'; if (reason.status === 404) return 'Đồ án hoặc bản ghi không còn tồn tại.'; if (reason.status === 400) return reason.problem?.detail || 'Dữ liệu không hợp lệ theo quy tắc hệ thống.' } return 'Chưa hoàn tất thao tác. Hãy thử tải lại.' }

export function ProjectGovernancePage() {
  const projectId = Number(useParams().projectId); const errorSummary = useRef<HTMLDivElement>(null)
  const [data, setData] = useState<Awaited<ReturnType<typeof loadData>> | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null)
  useEffect(() => { if (error) errorSummary.current?.focus() }, [error])
  const load = useCallback(async () => { if (!Number.isInteger(projectId) || projectId < 1) { setError('đồ án ID không hợp lệ.'); setLoading(false); return }; setLoading(true); try { setData(await loadData(projectId)); setError(null) } catch (reason) { setError(errorText(reason)) } finally { setLoading(false) } }, [projectId])
  useEffect(() => { void load() }, [load])
  const mutationLock = useRef(false)
  const run = async (operation: () => Promise<unknown>, success: string) => { if (mutationLock.current) return; mutationLock.current = true; setBusy(true); setError(null); setNotice(null); try { await operation(); await load(); setNotice(success) } catch (reason) { if (reason instanceof HttpError && reason.status === 409) await load(); setError(errorText(reason)) } finally { mutationLock.current = false; setBusy(false) } }
  return <WorkspacePage title="Điều phối đồ án" description="Theo dõi lịch báo cáo, việc cần làm sau trao đổi và minh chứng của nhóm." eyebrow={`Đồ án #${projectId}`} className="execution-page">
    {error && <div ref={errorSummary} tabIndex={-1} role="alert" className="rounded-lg border border-status-error-border bg-status-error-bg p-4 text-sm text-status-error-text"><strong>Chưa thể hoàn tất thao tác</strong><p className="mt-1">{error}</p><button type="button" className="mt-2 min-h-11 font-semibold underline" onClick={() => void load()}>Tải lại</button></div>}{notice && <p role="status" className="rounded-lg border border-status-success-border bg-status-success-bg p-4 text-sm text-status-success-text">{notice}</p>}{loading && <p role="status" className="rounded-lg border border-hairline bg-card p-4 text-sm">Đang tải thông tin điều phối…</p>}
    {data && <>{api.canManageProjectGovernance(data.governance) ? <ProjectGovernanceEditor projectId={projectId} cycles={data.cycles} actions={data.actions} sources={[...data.meetings.map(item => ({ value: `MEETING:${item.id}`, title: `Cuộc họp: ${item.title}` })), ...data.reports.map(item => ({ value: `PROGRESS_REPORT:${item.id}`, title: `Báo cáo #${item.id}` }))]} busy={busy} run={run} /> : <p className="rounded-lg border border-status-warning-border bg-status-warning-bg p-4 text-sm text-status-warning-text" role="status">Bạn có thể xem dữ liệu. Thao tác điều phối dành cho bộ môn chủ trì khi đồ án còn được chỉnh sửa.</p>}<section className="grid gap-5 xl:grid-cols-2"><CyclePanel projectId={projectId} data={data} busy={busy} run={run} readOnly /><ActionPanel projectId={projectId} data={data} busy={busy} run={run} readOnly /></section><EvidencePanel data={data} /><AssignmentManagementPanel projectId={projectId} canManage={api.canManageProjectGovernance(data.governance)} /></>}
  </WorkspacePage>
}
async function loadData(projectId: number) { const [project, cycles, actions, evidence, reports, meetings, governance] = await Promise.all([getProject(projectId), api.getReportingCycles(projectId), api.getProjectActionItems(projectId), api.getProjectEvidence(projectId), getProgressReports(projectId, { page: 1, pageSize: 100 }), getMeetings(projectId, { page: 1, pageSize: 100 }), api.getProjectGovernance(projectId)]); return { project, governance, cycles: cycles.items, actions: actions.items, evidence: evidence.items, reports: reports.items, meetings: meetings.items } }
function CyclePanel({ data }: PanelProps & { readOnly?: boolean }) { return <section className="workspace-surface p-5 sm:p-6"><h2 className="font-semibold">Lịch báo cáo hiện có</h2><ul className="mt-4 divide-y divide-hairline text-sm">{data.cycles.map(item => <li key={item.id} className="space-y-1 py-3"><strong>{item.reportType === 'WEEKLY' ? 'Hàng tuần' : 'Hàng tháng'} · {item.latePolicy === 'BLOCK' ? 'Không cho nộp trễ' : 'Đánh dấu nộp trễ'}</strong><p className="text-slate-600">{date(item.periodStart)} → {date(item.periodEnd)}</p><p className="text-slate-600">Hạn nộp: {date(item.deadline)}</p></li>)}</ul>{!data.cycles.length && <p className="mt-3 text-sm text-slate-500">Chưa có lịch báo cáo.</p>}</section> }
type PanelProps = { projectId: number; data: Awaited<ReturnType<typeof loadData>>; busy: boolean; run: (operation: () => Promise<unknown>, success: string) => Promise<void> }
function ActionPanel({ data, readOnly }: PanelProps & { readOnly?: boolean }) { return <section className="rounded-xl border border-hairline bg-card p-5"><h2 className="font-semibold text-slate-900">Công việc sau trao đổi</h2><p className="mt-1 text-sm text-slate-600">{readOnly ? 'Các công việc đã ghi nhận sau cuộc họp hoặc báo cáo.' : 'Action item hiện có.'}</p><ul className="mt-4 divide-y text-sm">{data.actions.map(item => <li key={item.id} className="py-3"><strong>{item.title}</strong><span className="block text-slate-600">{item.sourceType} #{item.meetingId ?? item.progressReportId} · {displayLabel(item.status)} · hạn {date(item.dueAt)}</span></li>)}{!data.actions.length && <li className="py-3 text-slate-600">Chưa có công việc sau trao đổi.</li>}</ul></section> }
function EvidencePanel({ data }: { data: Awaited<ReturnType<typeof loadData>> }) { return <section className="rounded-xl border border-hairline bg-card p-5"><h2 className="font-semibold text-slate-900">Sổ minh chứng đồ án</h2><p className="mt-1 text-sm leading-6 text-slate-600">Bổ sung minh chứng tại công việc tương ứng để giữ đúng nguồn dữ liệu.</p><ul className="mt-4 divide-y text-sm">{data.evidence.map(item => <li key={item.id} className="py-3"><strong>{item.sourceType} #{item.sourceId}</strong><span className="block text-slate-600">{item.classification} · xác minh {item.verificationStatus} · {date(item.submittedAt)}</span>{item.notes && <p className="mt-1 text-slate-600">{item.notes}</p>}</li>)}{!data.evidence.length && <li className="py-3 text-slate-600">Chưa có minh chứng.</li>}</ul></section> }
