import { useState, type FormEvent } from 'react'
import { useExecutionAccess } from '../execution/context/ExecutionAccessContext'
import { askProjectAssistant, type ProjectAssistantResponse } from './ai-api'
import { ProjectProgressAnalysisPanel } from './components/ProjectProgressAnalysisPanel'
import { HttpError } from '../../services/http/http-client'

export function ProjectAiPage() {
  const { project } = useExecutionAccess(); const [query, setQuery] = useState(''); const [answer, setAnswer] = useState<ProjectAssistantResponse | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const ask = async (event: FormEvent) => { event.preventDefault(); const value = query.trim(); if (!value || busy) return; setBusy(true); setError(null); setAnswer(null); try { setAnswer(await askProjectAssistant(project.id, value)) } catch (reason) { setError(reason instanceof HttpError && reason.status === 429 ? 'Yêu cầu đang vượt giới hạn. Hãy chờ một lúc rồi thử lại.' : reason instanceof HttpError && reason.status === 403 ? 'Backend không cấp quyền hỏi trợ lý cho đồ án này.' : 'Không thể nhận phản hồi từ trợ lý AI.') } finally { setBusy(false) } }
  return <main className="mx-auto max-w-5xl space-y-5 pb-12"><header><p className="font-mono text-xs font-semibold uppercase tracking-wide text-primary">AI assistant · advisory only</p><h1 className="mt-1 font-heading text-2xl font-bold text-slate-950">Trợ lý AI & phân tích đồ án</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Trợ lý chỉ dùng ngữ cảnh đồ án do Backend cấp trong một lượt hỏi. Phản hồi không là quyết định học vụ, không cập nhật dữ liệu và không lưu lịch sử hội thoại trên giao diện.</p></header><ProjectProgressAnalysisPanel projectId={project.id} /><section className="rounded-xl border border-hairline bg-card p-5 shadow-xs"><h2 className="font-heading text-lg font-semibold text-slate-950">Hỏi trợ lý theo đồ án</h2><p className="mt-1 text-sm text-slate-600">Hãy hỏi về tiến độ, công việc, báo cáo hoặc bước tiếp theo. Kiểm tra chứng cứ trước khi hành động.</p><form className="mt-4 space-y-3" onSubmit={event => void ask(event)}><label className="flex flex-col gap-1 text-sm font-medium text-slate-800" htmlFor="project-ai-query">Câu hỏi<textarea id="project-ai-query" value={query} onChange={event => setQuery(event.target.value)} rows={4} maxLength={2000} className="rounded-lg border border-hairline bg-card p-3 text-slate-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary" placeholder="Ví dụ: Những việc nào cần ưu tiên trong tuần này?" /></label><button type="submit" disabled={!query.trim() || busy} className="min-h-11 rounded-lg bg-primary px-4 text-sm font-semibold text-white hover:bg-primary-hover focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary disabled:cursor-not-allowed disabled:opacity-50">{busy ? 'Đang hỏi trợ lý…' : 'Gửi câu hỏi'}</button></form>{error && <p role="alert" className="mt-4 rounded-lg border border-status-error-border bg-status-error-bg p-3 text-sm text-status-error-text">{error}</p>}{answer && <AssistantAnswer answer={answer} />}</section></main>
}
function AssistantAnswer({ answer }: { answer: ProjectAssistantResponse }) { return <section aria-live="polite" className="mt-5 rounded-lg border border-primary-subtle bg-primary-subtle p-4"><p className="text-xs font-semibold uppercase tracking-wide text-primary">Phản hồi AI · phạm vi {answer.contextScope}</p>{answer.insufficientEvidence && <p role="status" className="mt-3 rounded-lg border border-status-warning-border bg-status-warning-bg p-3 text-sm text-status-warning-text">Chưa đủ chứng cứ cho một kết luận đáng tin cậy. Không suy diễn phản hồi này là xác nhận tiến độ hoặc rủi ro thấp.</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-800">{answer.answer}</p>{answer.limitationNote && <p className="mt-3 text-sm text-slate-700"><span className="font-semibold">Giới hạn:</span> {answer.limitationNote}</p>}<Evidence items={answer.evidence} /><p className="mt-3 text-xs text-slate-500">Tạo lúc {new Date(answer.generatedAt).toLocaleString('vi-VN')}</p></section> }
function Evidence({ items }: { items: ProjectAssistantResponse['evidence'] }) { if (!items.length) return <p className="mt-3 text-sm text-slate-600">Backend chưa trả chứng cứ tham chiếu.</p>; return <section className="mt-4"><h3 className="text-sm font-semibold text-slate-900">Chứng cứ Backend trả về</h3><ul className="mt-2 space-y-2 text-sm text-slate-700">{items.map(item => <li key={`${item.sourceType}-${item.sourceId}`} className="rounded-lg border border-hairline bg-card p-3"><span className="font-semibold">{item.title}</span><span className="ml-2 text-xs text-slate-500">{item.sourceType} #{item.sourceId}</span>{item.excerpt && <p className="mt-1">{item.excerpt}</p>}{item.periodOrDate && <p className="mt-1 text-xs text-slate-500">{item.periodOrDate}</p>}</li>)}</ul></section> }
