import { afterEach, describe, expect, it, vi } from 'vitest'
import * as tasks from '../tasks.api'

const jsonResponse = (body: unknown) => ({ ok: true, status: 200, statusText: 'OK', json: async () => body }) as unknown as Response
const noContent = () => ({ ok: true, status: 204, statusText: 'No Content', json: async () => { throw new Error('204 must not parse JSON') } }) as unknown as Response

describe('tasks api', () => {
  const originalFetch = globalThis.fetch
  afterEach(() => { globalThis.fetch = originalFetch })
  it('serializes supported task list filters in the API layer', async () => { globalThis.fetch = vi.fn().mockResolvedValue(jsonResponse({ items: [] })); await tasks.getProjectTasks(9, { milestoneId: 2, status: 'TODO', search: 'AI', isBlocked: true, page: 2, pageSize: 25 }); expect(globalThis.fetch).toHaveBeenCalledWith('/api/v1/tasks/project/9?page=2&pageSize=25&milestoneId=2&status=TODO&search=AI&isBlocked=true', expect.objectContaining({ method: 'GET' })) })
  it('uses JSON responses and sends only the update task contract fields', async () => { globalThis.fetch = vi.fn().mockResolvedValue(jsonResponse({ id: 3 })); await tasks.createTask({ milestoneId: 2, title: 'Task', assigneeUserIds: [7] }); await tasks.updateTask(3, { milestoneId: 2, title: 'Task', description: null, priority: 'HIGH', startAt: null, dueAt: null, parentTaskId: null }); const calls = (globalThis.fetch as ReturnType<typeof vi.fn>).mock.calls; expect(calls[0][1].body).toBe(JSON.stringify({ milestoneId: 2, title: 'Task', assigneeUserIds: [7] })); expect(JSON.parse(calls[1][1].body)).toEqual({ milestoneId: 2, title: 'Task', description: null, priority: 'HIGH', startAt: null, dueAt: null, parentTaskId: null }); expect(JSON.parse(calls[1][1].body)).not.toHaveProperty('assigneeUserIds') })
  it('parses TaskDto responses for task mutations while only task deletion is 204', async () => { const updatedTask = { id: 3, title: 'Updated task' }; globalThis.fetch = vi.fn().mockResolvedValueOnce(noContent()).mockResolvedValueOnce(jsonResponse(updatedTask)).mockResolvedValueOnce(jsonResponse(updatedTask)).mockResolvedValueOnce(jsonResponse(updatedTask)).mockResolvedValueOnce(jsonResponse(updatedTask)); await tasks.deleteTask(3); const assigned = await tasks.setTaskAssignees(3, [7]); const dependencyAdded = await tasks.addTaskDependency({ taskId: 3, dependsOnTaskId: 2, dependencyType: 'FINISH_TO_START' }); const dependencyRemoved = await tasks.removeTaskDependency(3, 2); const statusUpdated = await tasks.updateTaskStatus(3, { newStatus: 'DONE' }); expect([assigned, dependencyAdded, dependencyRemoved, statusUpdated]).toEqual([updatedTask, updatedTask, updatedTask, updatedTask]); expect((globalThis.fetch as ReturnType<typeof vi.fn>).mock.calls.map(([url, init]) => [url, init.method, init.body])).toEqual([['/api/v1/tasks/3', 'DELETE', undefined], ['/api/v1/tasks/3/assignees', 'POST', JSON.stringify([7])], ['/api/v1/tasks/dependency', 'POST', JSON.stringify({ taskId: 3, dependsOnTaskId: 2, dependencyType: 'FINISH_TO_START' })], ['/api/v1/tasks/3/dependency/2', 'DELETE', undefined], ['/api/v1/tasks/3/status', 'PUT', JSON.stringify({ newStatus: 'DONE' })]]) })
  it('uses history, timeline, progress, and overdue-blocked reads', async () => { globalThis.fetch = vi.fn().mockResolvedValue(jsonResponse({})); await tasks.getTaskHistory(3); await tasks.getOverdueBlockedTasks(9); await tasks.getProjectTimeline(9); await tasks.getProjectProgressSummary(9); expect((globalThis.fetch as ReturnType<typeof vi.fn>).mock.calls.map(([url]) => url)).toEqual(['/api/v1/tasks/3/history', '/api/v1/tasks/project/9/overdue-blocked', '/api/v1/tasks/project/9/timeline', '/api/v1/tasks/project/9/progress-summary']) })
})
