import { useCallback, useEffect, useState } from 'react'
import { HttpError } from '../../../services/http/http-client'
import { getProjectProgressAnalysis, type ProjectProgressAnalysis } from '../ai-api'

export function ProjectProgressAnalysisPanel({ projectId, compact = false }: { projectId: number; compact?: boolean }) {
  const [analysis, setAnalysis] = useState<ProjectProgressAnalysis | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); try { setAnalysis(await getProjectProgressAnalysis(projectId)); setError(null) } catch (reason) { setError(errorMessage(reason)) } finally { setLoading(false) } }, [projectId])
  useEffect(() => { void load() }, [load])
  if (loading) return <section aria-label="Phân tích tiến độ" className="rounded-xl border border-hairline bg-card p-5 shadow-xs"><p role="status" className="text-sm text-slate-600">Đang tải phân tích tiến độ từ Backend…</p></section>
  if (error) return <section aria-label="Phân tích tiến độ" className="rounded-xl border border-status-error-border bg-status-error-bg p-5 text-sm text-status-error-text"><p role="alert">{error}</p><button type="button" className="mt-2 min-h-11 font-semibold underline underline-offset-4" onClick={() => void load()}>Tải lại phân tích</button></section>
  if (!analysis) return null
  const insufficient = analysis.dataStatus === 'INSUFFICIENT_DATA'
  const riskClass = insufficient ? 'border-status-warning-border bg-status-warning-bg text-status-warning-text' : analysis.riskLevel === 'HIGH' ? 'border-status-error-border bg-status-error-bg text-status-error-text' : analysis.riskLevel === 'MEDIUM' ? 'border-status-warning-border bg-status-warning-bg text-status-warning-text' : 'border-status-success-border bg-status-success-bg text-status-success-text'
  return <section aria-labelledby={`progress-analysis-${projectId}`} className="rounded-xl border border-hairline bg-card p-5 shadow-xs"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">Phân tích tư vấn</p><h2 id={`progress-analysis-${projectId}`} className="mt-1 font-heading text-lg font-semibold text-slate-950">Rủi ro và tiến độ đồ án</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-600">Kết quả dựa trên dữ liệu Backend tại thời điểm tạo; không xếp hạng GVHD, không thay đổi trạng thái, rubric hay điểm.</p></div><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${riskClass}`}>{insufficient ? 'Chưa đủ dữ liệu' : `Rủi ro: ${analysis.riskLevel}`}</span></div>{insufficient ? <p role="status" className="mt-4 rounded-lg border border-status-warning-border bg-status-warning-bg p-3 text-sm text-status-warning-text">Backend trả về INSUFFICIENT_DATA. Không diễn giải đây là rủi ro thấp; hãy bổ sung dữ liệu thực thi và báo cáo trước khi dùng kết quả để tham khảo.</p> : <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Tiến độ" value={`${analysis.progressSummary.progressPercentage}%`} /><Metric label="Task quá hạn" value={analysis.progressSummary.overdueTasks} /><Metric label="Task vướng mắc" value={analysis.progressSummary.blockedTasks} /><Metric label="Độ tin cậy" value={analysis.confidence === null ? 'Chưa có' : `${Math.round(analysis.confidence * 100)}%`} /></div>}{!compact && <><InfoList title="Lý do / tín hiệu" items={analysis.factors.map(factor => `${factor.severity}: ${factor.explanation}`)} empty="Backend chưa trả tín hiệu rủi ro cụ thể." /><InfoList title="Khuyến nghị" items={analysis.recommendations} empty="Backend chưa trả khuyến nghị." /></>}{analysis.limitations && <p className="mt-4 rounded-lg border border-hairline bg-canvas p-3 text-sm text-slate-700"><span className="font-semibold">Giới hạn:</span> {analysis.limitations}</p>}<p className="mt-4 text-xs text-slate-500">dataStatus: {analysis.dataStatus} · trend: {analysis.trendStatus} · rule {analysis.ruleVersion} · tạo lúc {formatDate(analysis.generatedAtUtc)}</p></section>
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border border-hairline bg-canvas p-3"><p className="text-xs text-slate-600">{label}</p><p className="mt-1 text-lg font-bold tabular-nums text-slate-950">{value}</p></div> }
function InfoList({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <section className="mt-5"><h3 className="font-semibold text-slate-950">{title}</h3>{items.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-slate-700">{items.map((item, index) => <li key={`${title}-${index}`}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-slate-600">{empty}</p>}</section> }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short' }).format(date) }
function errorMessage(reason: unknown) { if (reason instanceof HttpError) { if (reason.status === 403) return 'Backend không cấp quyền xem phân tích của đồ án này.'; if (reason.status === 404) return 'Không tìm thấy đồ án hoặc dữ liệu phân tích.'; if (reason.status === 401) return 'Phiên đăng nhập đã hết hạn.' }; return 'Không thể tải phân tích từ Backend.' }
