import { useCallback, useEffect, useState } from 'react'
import { HttpError } from '../../../services/http/http-client'
import { getReportAiSummary, type ReportAiSummary as Summary } from '../ai-api'

export function ReportAiSummary({ projectId, reportId }: { projectId: number; reportId: number }) {
  const [summary, setSummary] = useState<Summary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); try { setSummary(await getReportAiSummary(projectId, reportId)); setError(null) } catch (reason) { setError(reason instanceof HttpError && reason.status === 403 ? 'Backend không cấp quyền xem tóm tắt AI của báo cáo này.' : 'Không thể tải tóm tắt AI từ Backend.') } finally { setLoading(false) } }, [projectId, reportId])
  useEffect(() => { void load() }, [load])
  return <section className="report-panel" aria-labelledby="ai-report-summary"><div className="report-section-heading"><h2 id="ai-report-summary">Tóm tắt AI tham khảo</h2><span>AI</span></div><p className="report-help">Nội dung do Backend tạo từ báo cáo và chứng cứ được cấp quyền; không thay thế nhận xét GVHD hay quyết định học vụ.</p>{loading ? <p role="status" className="mt-3 text-sm">Đang tải tóm tắt…</p> : error ? <div role="alert" className="mt-3 text-sm"><p>{error}</p><button type="button" className="report-text-button" onClick={() => void load()}>Tải lại tóm tắt</button></div> : summary && <><dl className="mt-3 space-y-3 text-sm">{([['Đã hoàn thành', summary.summary.completed], ['Đang thực hiện', summary.summary.inProgress], ['Vướng mắc', summary.summary.blockers], ['Rủi ro', summary.summary.risks], ['Việc tiếp theo', summary.summary.nextActions]] as const).map(([label, value]) => <div key={label}><dt className="font-semibold text-slate-900">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-slate-700">{value || 'Backend chưa có nội dung.'}</dd></div>)}</dl>{summary.limitationNote && <p className="mt-3 text-sm text-slate-700"><strong>Giới hạn:</strong> {summary.limitationNote}</p>}<p className="mt-3 text-xs text-slate-500">Phạm vi {summary.contextScope} · {summary.evidence.length} chứng cứ · tạo lúc {new Date(summary.generatedAt).toLocaleString('vi-VN')}</p></>}</section>
}
