export const endpoints = {
  system: '/system',
  projectLifecycle: '/projects/lifecycle',
  progressAnalysis: '/ai/insights/progress',
  authLogin: '/v1/auth/login',
  authRefresh: '/v1/auth/refresh',
  authLogout: '/v1/auth/logout',
  authCurrentUser: '/v1/auth/me',
  authWorkflowContext: '/v1/auth/me/context',
  academicHierarchy: '/v1/academic/hierarchy',
  academicOrganizations: '/v1/academic/organizations',
  academicDepartments: '/v1/academic/departments',
  academicMajors: '/v1/academic/majors',
  academicSemesters: '/v1/academic/semesters',
  academicProjectPeriods: '/v1/academic/project-periods',
  users: '/v1/users',
  securityRoles: '/v1/security/roles',
  securityPermissions: '/v1/security/permissions',
  securityAuditLogs: '/v1/security/audit-logs',
  projectReviewQueue: '/v1/projects/review-queue',
  supervisors: '/v1/supervisors',
  topics: '/v1/topics',
} as const
