import { endpoints } from '../../../services/api/endpoints'
import { httpGet, httpPatch, httpPost, httpPut } from '../../../services/http/http-client'
import type { GovernanceFilters, PagedResult, ProjectPeriod, ProjectPeriodDraft, Semester, SemesterDraft } from '../types/governance.types'

function query(path:string, values:Record<string,string|number|undefined>) { const q=new URLSearchParams(); Object.entries(values).forEach(([key,value])=>{ if(value!==undefined && value!=='') q.set(key,String(value)) }); return q.size ? `${path}?${q}` : path }
export function getSemesters(token:string, filters:GovernanceFilters, signal?:AbortSignal) { return httpGet<PagedResult<Semester>>(query(endpoints.academicSemesters,{search:filters.search,status:filters.status,page:1,pageSize:100}),{accessToken:token,signal}) }
export function getProjectPeriods(token:string, filters:GovernanceFilters, signal?:AbortSignal) { return httpGet<PagedResult<ProjectPeriod>>(query(endpoints.academicProjectPeriods,{semesterId:filters.semesterId,search:filters.search,status:filters.status,page:1,pageSize:100}),{accessToken:token,signal}) }
export function saveSemester(draft:SemesterDraft, token:string) { const body={code:draft.code,name:draft.name,startDate:draft.startDate,endDate:draft.endDate}; return draft.id ? httpPut<Semester>(`${endpoints.academicSemesters}/${draft.id}`,body,{accessToken:token}) : httpPost<Semester>(endpoints.academicSemesters,{...body,organizationId:draft.organizationId},{accessToken:token}) }
export function saveProjectPeriod(draft:ProjectPeriodDraft, token:string) { const body={code:draft.code,name:draft.name,periodType:draft.periodType,startAt:draft.startAt,endAt:draft.endAt,minTeamSize:draft.minTeamSize,maxTeamSize:draft.maxTeamSize,minDistinctMajors:draft.minDistinctMajors,maxProjectsPerSupervisor:draft.maxProjectsPerSupervisor,milestoneTemplateId:null,rubricId:draft.rubricId}; return draft.id ? httpPut<ProjectPeriod>(`${endpoints.academicProjectPeriods}/${draft.id}`,body,{accessToken:token}) : httpPost<ProjectPeriod>(endpoints.academicProjectPeriods,{...body,academicSemesterId:draft.academicSemesterId},{accessToken:token}) }
export function setGovernanceStatus(kind:'semester'|'period', id:number, status:string, expectedStatus:string, token:string) { const path=kind==='semester'?endpoints.academicSemesters:endpoints.academicProjectPeriods; return httpPatch(`${path}/${id}/status`,{status,expectedStatus},{accessToken:token}) }
