import { afterEach, describe, expect, it, vi } from 'vitest'
import { getProjectPeriods, saveProjectPeriod, saveSemester, setGovernanceStatus } from './governance-api'
afterEach(()=>vi.unstubAllGlobals())
const ok=(value:unknown)=>({ok:true,json:async()=>value})
describe('governance API contracts',()=>{
 it('loads periods by semester using documented filters',async()=>{const fetchMock=vi.fn().mockResolvedValue(ok({items:[],page:1,pageSize:100,totalCount:0}));vi.stubGlobal('fetch',fetchMock);await getProjectPeriods('token',{semesterId:2,search:'review',status:'UPCOMING'});expect(fetchMock).toHaveBeenCalledWith('/api/v1/academic/project-periods?semesterId=2&search=review&status=UPCOMING&page=1&pageSize=100',expect.objectContaining({headers:expect.objectContaining({Authorization:'Bearer token'})}))})
 it('sends policy fields with a period create request',async()=>{const fetchMock=vi.fn().mockResolvedValue(ok({id:1}));vi.stubGlobal('fetch',fetchMock);await saveProjectPeriod({academicSemesterId:2,code:'REG-01',name:'Registration',periodType:'REGISTRATION',startAt:'2026-01-01T00:00',endAt:'2026-01-02T00:00',minTeamSize:3,maxTeamSize:5,minDistinctMajors:1,maxProjectsPerSupervisor:5,rubricId:null},'token');expect(fetchMock).toHaveBeenCalledWith('/api/v1/academic/project-periods',expect.objectContaining({method:'POST',body:expect.stringContaining('"academicSemesterId":2')}))})
 it('updates a semester without allowing its organization ownership to change',async()=>{const fetchMock=vi.fn().mockResolvedValue(ok({id:1}));vi.stubGlobal('fetch',fetchMock);await saveSemester({id:1,organizationId:99,code:'FA26',name:'Fall 2026',startDate:'2026-09-01',endDate:'2026-12-31'},'token');expect(fetchMock).toHaveBeenCalledWith('/api/v1/academic/semesters/1',expect.objectContaining({method:'PUT',body:JSON.stringify({code:'FA26',name:'Fall 2026',startDate:'2026-09-01',endDate:'2026-12-31'})}))})
 it('uses expected status for backend-controlled transitions',async()=>{const fetchMock=vi.fn().mockResolvedValue(ok({id:1}));vi.stubGlobal('fetch',fetchMock);await setGovernanceStatus('period',1,'UPCOMING','DRAFT','token');expect(fetchMock).toHaveBeenCalledWith('/api/v1/academic/project-periods/1/status',expect.objectContaining({method:'PATCH',body:JSON.stringify({status:'UPCOMING',expectedStatus:'DRAFT'})}))})
})
