import { useCallback, useEffect, useRef, useState } from 'react'
import * as api from '../../projects/api/discipline-governance-api'
import { HttpError } from '../../../services/http/http-client'

export function TaskDisciplinePanel({ taskId, majors, canManage }: { taskId: number; majors: Array<{ majorId: number; majorCode: string; majorName: string }>; canManage: boolean }) {
  const [data, setData] = useState<api.TaskDisciplines | null>(null); const [items, setItems] = useState<api.TaskDiscipline[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const request = useRef(0)
  const load = useCallback((preserveIntent = false) => { const version = ++request.current; setError(''); setData(null); api.getTaskDisciplines(taskId).then(next => { if (version !== request.current) return; setData(next); setItems(current => preserveIntent ? current : next.items) }).catch(reason => { if (version !== request.current) return; setError(reason instanceof HttpError && reason.status === 403 ? 'Bạn không có quyền xem chuyên ngành phụ trách công việc này.' : 'Chưa tải được chuyên ngành phụ trách.') }) }, [taskId])
  useEffect(() => { const pending = request; load(); return () => { pending.current++ } }, [load])
  const save = async () => { if (!data || !canManage) return; setBusy(true); setError(''); try { const saved = await api.replaceTaskDisciplines(taskId, data.concurrencyToken, items); setData(saved); setItems(saved.items) } catch (reason) { if (reason instanceof HttpError && reason.status === 409) load(true); setError('Chưa lưu được phân loại. Công việc có thể đã thay đổi; nội dung bạn chọn được giữ lại để kiểm tra.') } finally { setBusy(false) } }
  return <section className="ex-panel"><div className="ex-panel-heading"><h2>Phân loại chuyên ngành</h2></div><div className="ex-padding">{error && <p role="alert" className="ex-notice ex-notice-error">{error}</p>}{!data ? error ? <button type="button" className="ex-button" onClick={() => load()}>Thử lại</button> : <p className="ex-muted">Đang tải…</p> : <><p className="ex-muted">{data.classification === 'CLASSIFIED' ? 'Đã phân loại' : 'Chưa phân loại'}. Chọn ngành phụ trách phần việc này trong các ngành tham gia đồ án.</p>{items.map((item, index) => <div key={index} className="task-discipline-row"><select aria-label={`Chuyên ngành phụ trách ${index + 1}`} value={item.majorId} disabled={busy || !canManage} onChange={event => setItems(current => current.map((row, i) => i === index ? { ...row, majorId: Number(event.target.value) } : row))}><option value="">Chọn chuyên ngành</option>{majors.map(major => <option key={major.majorId} value={major.majorId} disabled={items.some((row, i) => i !== index && row.majorId === major.majorId)}>{major.majorCode} · {major.majorName}</option>)}</select><select aria-label={`Vai trò chuyên ngành ${index + 1}`} value={item.role} disabled={busy || !canManage} onChange={event => setItems(current => current.map((row, i) => i === index ? { ...row, role: event.target.value } : row))}><option value="PRIMARY">Chủ trì</option><option value="SUPPORTING">Phối hợp</option></select>{canManage && <button type="button" className="ex-text-button ex-danger-text" disabled={busy} onClick={() => setItems(current => current.filter((_, i) => i !== index))}>Xóa</button>}</div>)}{canManage ? <div className="ex-form-footer"><button type="button" className="ex-button" disabled={busy || !majors.some(major => !items.some(item => item.majorId === major.majorId))} onClick={() => setItems(current => [...current, { majorId: majors.find(major => !current.some(item => item.majorId === major.majorId))?.majorId ?? 0, role: 'PRIMARY' }])}>Thêm chuyên ngành</button><button type="button" className="ex-button ex-button-primary" disabled={busy || items.some(x => !x.majorId) || new Set(items.map(x => x.majorId)).size !== items.length} onClick={() => void save()}>{busy ? 'Đang lưu…' : 'Lưu phân loại'}</button></div> : <p className="ex-muted mt-3">Phân loại chỉ đọc; hệ thống chưa xác nhận quyền ghi cho công việc này.</p>}</>}</div></section>
}
