import { useEffect, useState } from 'react'
import * as api from '../../projects/api/discipline-governance-api'
import { HttpError } from '../../../services/http/http-client'

export function TaskDisciplinePanel({ taskId, majors }: { taskId: number; majors: Array<{ majorId: number; majorCode: string; majorName: string }> }) {
  const [data, setData] = useState<api.TaskDisciplines | null>(null); const [items, setItems] = useState<api.TaskDiscipline[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = () => { setData(null); api.getTaskDisciplines(taskId).then(next => { setData(next); setItems(next.items) }).catch(reason => setError(reason instanceof HttpError && reason.status === 403 ? 'Backend không cấp quyền xem discipline của task.' : 'Không thể tải task discipline.')) }
  useEffect(load, [taskId])
  const save = async () => { if (!data) return; setBusy(true); setError(''); try { const saved = await api.replaceTaskDisciplines(taskId, data.concurrencyToken, items); setData(saved); setItems(saved.items) } catch (reason) { if (reason instanceof HttpError && reason.status === 409) load(); setError('Không thể lưu discipline: task, phạm vi hoặc token đã thay đổi.') } finally { setBusy(false) } }
  return <section className="ex-panel"><div className="ex-panel-heading"><h2>Phân loại chuyên ngành</h2></div><div className="ex-padding">{error && <p role="alert" className="ex-notice ex-notice-error">{error}</p>}{!data ? <p className="ex-muted">Đang tải…</p> : <><p className="ex-muted">{data.classification}. Backend chỉ chấp nhận major thuộc scope đồ án và quyền ghi phù hợp.</p>{items.map((item, index) => <div key={`${item.majorId}-${index}`} className="mt-2 flex gap-2"><select value={item.majorId} disabled={busy} onChange={event => setItems(current => current.map((row, i) => i === index ? { ...row, majorId: Number(event.target.value) } : row))}><option value="">Chọn major</option>{majors.map(major => <option key={major.majorId} value={major.majorId}>{major.majorCode} · {major.majorName}</option>)}</select><select value={item.role} disabled={busy} onChange={event => setItems(current => current.map((row, i) => i === index ? { ...row, role: event.target.value } : row))}><option>PRIMARY</option><option>SUPPORTING</option></select><button type="button" className="ex-text-button ex-danger-text" disabled={busy} onClick={() => setItems(current => current.filter((_, i) => i !== index))}>Xóa</button></div>)}<div className="ex-form-footer"><button type="button" className="ex-button" disabled={busy} onClick={() => setItems(current => [...current, { majorId: majors[0]?.majorId ?? 0, role: 'PRIMARY' }])}>Thêm major</button><button type="button" className="ex-button ex-button-primary" disabled={busy || items.some(x => !x.majorId)} onClick={() => void save()}>{busy ? 'Đang lưu…' : 'Lưu discipline'}</button></div></>}</div></section>
}
