import type { StudentNavigationStep } from '../types/student-journey.types'

export const studentNavigation: readonly StudentNavigationStep[] = [
  {
    state: 'NO_TEAM',
    label: 'No team',
    route: '/projects/lifecycle',
    availability: 'planned',
    plannedRoute: '/team/create',
    action: 'Create or join team',
  },
  {
    state: 'TEAM_FORMING',
    label: 'Team forming',
    route: '/projects/lifecycle',
    availability: 'planned',
    plannedRoute: '/team',
    action: 'Invite member',
  },
  {
    state: 'TEAM_ELIGIBLE',
    label: 'Team eligible',
    route: '/projects/lifecycle',
    availability: 'planned',
    plannedRoute: '/project/register',
    action: 'Register project',
  },
  {
    state: 'PROJECT_PENDING',
    label: 'Project pending',
    route: '/projects/lifecycle',
    availability: 'planned',
    plannedRoute: '/project/status',
    action: 'View status',
  },
  {
    state: 'REVISION_REQUIRED',
    label: 'Revision required',
    route: '/projects/lifecycle',
    availability: 'planned',
    plannedRoute: '/project/edit',
    action: 'Update and resubmit',
  },
  {
    state: 'SUPERVISOR_PENDING',
    label: 'Awaiting supervisor',
    route: '/projects/lifecycle',
    availability: 'planned',
    plannedRoute: '/project/supervisor',
    action: 'Request supervisor',
  },
  {
    state: 'ACTIVE',
    label: 'Project active',
    route: '/project/workspace',
    availability: 'available',
    action: 'Open workspace',
  },
  {
    state: 'FINAL_SUBMISSION',
    label: 'Final submission',
    route: '/projects/lifecycle',
    availability: 'planned',
    plannedRoute: '/project/final',
    action: 'Complete checklist',
  },
  {
    state: 'COMPLETED',
    label: 'Completed or archived',
    route: '/projects/lifecycle',
    availability: 'planned',
    plannedRoute: '/project/result',
    action: 'View result',
  },
]
