import { useEffect, useState } from 'react'
import * as api from '../../projects/api/discipline-governance-api'
import type { TeamAcademicScopeDto } from '../../../types/backend'
import { HttpError } from '../../../services/http/http-client'

export function StructuredResponsibilitiesPanel({ teamId, scope, onSaved }: { teamId: number; scope: TeamAcademicScopeDto; onSaved: () => Promise<void> }) {
  const [majorId, setMajorId] = useState(scope.requirements[0]?.majorId ?? 0); const [data, setData] = useState<api.ResponsibilityList | null>(null); const [rows, setRows] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const load = () => { if (!majorId) return; setData(null); setError(''); api.getTeamResponsibilities(teamId, majorId).then(next => { setData(next); setRows(next.items.map(x => x.content)) }).catch(reason => setError(reason instanceof HttpError && reason.status === 403 ? 'Hệ thống không cấp quyền xem trách nhiệm này.' : 'Không thể tải trách nhiệm theo chuyên ngành.')) }
  useEffect(load, [teamId, majorId])
  const save = async () => { if (!data?.concurrencyToken || data.isSnapshot) return; const items = rows.map(x => x.trim()).filter(Boolean).map((content, sortOrder) => ({ content, sortOrder })); setBusy(true); setError(''); try { await api.replaceTeamResponsibilities(teamId, majorId, data.concurrencyToken, items); await onSaved(); setNotice('Đã lưu phân công và cập nhật điều kiện của nhóm.'); load() } catch (reason) { if (reason instanceof HttpError && reason.status === 409) load(); setError('Chưa thể lưu vì thông tin nhóm đã thay đổi. Hãy tải lại và kiểm tra phân công.') } finally { setBusy(false) } }
  return <section className="mt-5 rounded-xl border border-hairline bg-card p-5"><h3 className="font-semibold text-slate-900">Trách nhiệm theo chuyên ngành</h3><p className="mt-1 text-sm text-slate-600">Phân công được lưu cùng đề cương khi nộp. Bạn chỉ có thể sửa trước khi chốt.</p><label className="mt-3 block text-sm">Chuyên ngành<select value={majorId} onChange={event => setMajorId(Number(event.target.value))} className="mt-1 min-h-11 w-full rounded-lg border border-hairline px-3">{scope.requirements.map(x => <option key={x.majorId} value={x.majorId}>Chuyên ngành #{x.majorId}</option>)}</select></label>{error && <p role="alert" className="mt-3 text-sm text-status-error-text">{error}</p>}{notice && <p role="status" className="mt-3 text-sm text-status-success-text">{notice}</p>}{!data ? <p role="status" className="mt-3 text-sm">Đang tải…</p> : !data.isAvailable ? <p className="mt-3 text-sm">Chưa có phân công trách nhiệm cho chuyên ngành này.</p> : <><div className="mt-3 space-y-2">{rows.map((row, index) => <div key={index} className="flex gap-2"><input value={row} disabled={data.isSnapshot || busy} onChange={event => setRows(current => current.map((item, i) => i === index ? event.target.value : item))} className="min-h-11 min-w-0 flex-1 rounded-lg border border-hairline px-3" /><button type="button" disabled={data.isSnapshot || busy} onClick={() => setRows(current => current.filter((_, i) => i !== index))} className="min-h-11 px-3 text-sm font-semibold text-status-error-text">Xóa</button></div>)}</div>{!data.isSnapshot && <div className="mt-3 flex gap-3"><button type="button" onClick={() => setRows(current => [...current, ''])} className="min-h-11 rounded-lg border border-hairline px-3 text-sm font-semibold">Thêm trách nhiệm</button><button type="button" disabled={busy || !data.concurrencyToken} onClick={() => void save()} className="min-h-11 rounded-lg bg-primary px-4 text-sm font-semibold text-white disabled:opacity-50">Lưu</button></div>}{data.isSnapshot && <p className="mt-3 text-sm text-status-warning-text">Phân công đã được chốt cùng đề cương và chỉ có thể xem.</p>}</>}</section>
}
