import { HttpError } from '../../../services/http/http-client'
import { useEffect, useState } from 'react'
import { getMyAcademicProfile, type AcademicProfile } from '../api/profile-verification-api'
import { academicProfileStatus } from '../api/profile-verification-api'
export function AcademicProfileSummary() {
  const [profile, setProfile] = useState<AcademicProfile | null>(null), [error, setError] = useState<'missing' | 'failed' | null>(null), [revision, setRevision] = useState(0)
  useEffect(() => { let active = true; setError(null); void getMyAcademicProfile().then(result => { if (active) setProfile(result) }).catch(reason => { if (active) setError(reason instanceof HttpError && reason.status === 404 ? 'missing' : 'failed') }); return () => { active = false } }, [revision])
  return <section className="border-t border-hairline py-5" aria-labelledby="academic-profile-title"><h3 id="academic-profile-title" className="text-sm font-semibold">Thông tin học vụ</h3>{error === 'missing' ? <p className="mt-2 text-sm text-slate-600">Tài khoản chưa có hồ sơ học vụ.</p> : error ? <p className="mt-2 text-sm text-slate-600">Chưa tải được hồ sơ học vụ. <button type="button" className="font-semibold text-primary" onClick={() => setRevision(revision + 1)}>Thử lại</button></p> : profile ? <><dl className="mt-3 grid gap-4 sm:grid-cols-3"><div><dt className="text-xs text-slate-500">Bộ môn</dt><dd className="mt-1 text-sm font-medium">{profile.departmentName || 'Chưa cập nhật'}</dd></div><div><dt className="text-xs text-slate-500">Chuyên ngành</dt><dd className="mt-1 text-sm font-medium">{profile.majorName || 'Chưa cập nhật'}</dd></div><div><dt className="text-xs text-slate-500">Xác minh</dt><dd className="mt-1 text-sm font-medium">{academicProfileStatus(profile.status)}</dd></div></dl>{profile.rejectionReason && <p className="mt-3 text-sm text-amber-800">Cần bổ sung: {profile.rejectionReason}</p>}</> : <p role="status" className="mt-2 text-sm text-slate-500">Đang tải thông tin học vụ…</p>}</section>
}
