import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { TopicManagementPage } from './TopicManagementPage'
const hook = vi.hoisted(() => ({ useTopics: vi.fn() }))
vi.mock('../hooks/useTopics', () => hook)
vi.mock('../hooks/useTopicCatalog', () => ({ useTopicCatalog: () => ({ department: { id: 2, name: 'Computer Science' }, periods: [{ id: 1, semesterCode: 'FA26', name: 'Registration' }], majors: [{ id: 3, name: 'SE · Software Engineering', departmentId: 2 }, { id: 7, name: 'AI · Artificial Intelligence', departmentId: 2 }], loading: false, error: null, retry: () => undefined }) }))
afterEach(cleanup)
const topic = { id: 4, code: 'AI-4', status: 'DRAFT' as const, projectPeriodId: 1, academicSemesterId: 1, leadDepartmentId: 2, leadDepartmentName: 'Computer Science', title: 'AI Assist', description: 'Description', problemStatement: null, objectives: null, expectedOutput: null, domain: null, technologies: [], keywords: [], projectMode: 'SINGLE_MAJOR' as const, primaryMajorId: 3, requirements: [{ majorId: 3, majorName: 'Software Engineering', minMembers: 1, maxMembers: 1, responsibility: 'Lead' }], concurrencyToken: 'token', closeReason: null }
const state = (overrides = {}) => ({ items: [topic], page: 1, pageSize: 20, totalCount: 1, current: null, filters: { status: 'DRAFT' as const, page: 1, pageSize: 20 }, setFilters: vi.fn(), loading: false, error: null, saving: false, refresh: vi.fn(), create: vi.fn().mockResolvedValue(topic), update: vi.fn().mockResolvedValue(topic), publish: vi.fn().mockResolvedValue(topic), close: vi.fn().mockResolvedValue(topic), isUnauthorized: false, isForbidden: false, ...overrides })
function page(path = '/department/topics') { return render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/department/topics" element={<TopicManagementPage />} /><Route path="/department/topics/:id" element={<TopicManagementPage />} /></Routes></MemoryRouter>) }
beforeEach(() => hook.useTopics.mockReturnValue(state()))
describe('TopicManagementPage', () => {
  it('renders directory and server filter resets', () => {
    const current = state(); hook.useTopics.mockReturnValue(current); page()
    expect(screen.getByText('AI Assist')).toBeTruthy()
    fireEvent.change(screen.getByPlaceholderText('Mã hoặc tên đề tài'), { target: { value: 'AI' } })
    fireEvent.change(screen.getByLabelText('Trạng thái đề tài'), { target: { value: 'PUBLISHED' } })
    expect(current.setFilters).toHaveBeenCalledWith(expect.objectContaining({ search: 'AI', page: 1 }))
    expect(current.setFilters).toHaveBeenLastCalledWith(expect.objectContaining({ status: 'PUBLISHED' }))
  })
  it('saves full proposal content and confirms publish/close with reason', async () => {
    const current = state({ current: topic }); hook.useTopics.mockReturnValue(current); page('/department/topics/4')
    expect(screen.getByText('Software Engineering: 1–1 · Lead')).toBeTruthy()
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'Edited' } })
    fireEvent.change(screen.getByLabelText('Bối cảnh và vấn đề'), { target: { value: 'Problem context' } })
    fireEvent.change(screen.getByLabelText('Mục tiêu'), { target: { value: 'Goals' } })
    fireEvent.change(screen.getByLabelText('Công nghệ (phân cách bằng dấu phẩy)'), { target: { value: 'React, .NET' } })
    fireEvent.click(screen.getByRole('button', { name: 'Lưu bản nháp' }))
    expect(current.update).toHaveBeenCalledWith(expect.objectContaining({ title: 'Edited', problemStatement: 'Problem context', objectives: 'Goals', technologies: ['React', '.NET'] }))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Công bố' }).hasAttribute('disabled')).toBe(false))
    fireEvent.click(screen.getByRole('button', { name: 'Công bố' }))
    expect(current.publish).not.toHaveBeenCalled()
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Công bố đề tài' }))
    await waitFor(() => expect(current.publish).toHaveBeenCalledOnce())
    fireEvent.click(screen.getByRole('button', { name: 'Đóng đề tài' }))
    fireEvent.change(within(screen.getByRole('dialog')).getByRole('textbox'), { target: { value: 'Finished' } })
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Đóng đề tài' }))
    await waitFor(() => expect(current.close).toHaveBeenCalledWith('Finished'))
  })
  it('creates a scoped draft from catalog selections and editable major responsibilities', async () => {
    const current = state(); hook.useTopics.mockReturnValue(current); page()
    fireEvent.click(screen.getByText('Tạo đề tài mới'))
    fireEvent.change(screen.getByLabelText('Kỳ đăng ký'), { target: { value: '1' } })
    fireEvent.change(screen.getByLabelText('Mã đề tài'), { target: { value: 'NEW-1' } })
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'New proposal' } })
    fireEvent.change(screen.getByLabelText('Ngành chính'), { target: { value: '3' } })
    fireEvent.click(screen.getByRole('button', { name: 'Thêm ngành yêu cầu' }))
    fireEvent.change(screen.getByLabelText('Ngành yêu cầu 1'), { target: { value: '3' } })
    fireEvent.change(screen.getByLabelText('Tối đa 1'), { target: { value: '3' } })
    fireEvent.change(screen.getByLabelText('Trách nhiệm 1'), { target: { value: 'Build software' } })
    fireEvent.click(screen.getByRole('button', { name: 'Tạo bản nháp' }))
    await waitFor(() => expect(current.create).toHaveBeenCalledWith(expect.objectContaining({ projectPeriodId: 1, leadDepartmentId: 2, code: 'NEW-1', content: expect.objectContaining({ title: 'New proposal', requirements: [{ majorId: 3, minMembers: 1, maxMembers: 3, responsibility: 'Build software' }] }) })))
  })
  it('rejects an incomplete interdisciplinary scope before submitting', async () => {
    const current = state({ current: topic }); hook.useTopics.mockReturnValue(current); page('/department/topics/4')
    fireEvent.change(screen.getByLabelText('Hình thức đồ án'), { target: { value: 'INTERDISCIPLINARY' } })
    fireEvent.click(screen.getByRole('button', { name: 'Lưu bản nháp' }))
    expect((await screen.findByRole('alert')).textContent).toContain('ít nhất hai ngành')
    expect(current.update).not.toHaveBeenCalled()
  })
  it('connects draft errors to fields and focuses the summary link target', async () => {
    const current = state(); hook.useTopics.mockReturnValue(current); page()
    fireEvent.click(screen.getByText('Tạo đề tài mới'))
    fireEvent.click(screen.getByRole('button', { name: 'Tạo bản nháp' }))
    const summary = await screen.findByRole('alert')
    const title = screen.getByLabelText('Tên đề tài')
    expect(title.getAttribute('aria-invalid')).toBe('true')
    expect(document.getElementById(title.getAttribute('aria-describedby')!)).toHaveProperty('textContent', 'Nhập tên đề tài.')
    fireEvent.click(within(summary).getByRole('link', { name: 'Nhập tên đề tài.' }))
    expect(document.activeElement).toBe(title)
    expect(current.create).not.toHaveBeenCalled()
  })
  it('prevents publication of an older saved version while draft edits are unsaved', () => {
    const current = state({ current: topic }); hook.useTopics.mockReturnValue(current); page('/department/topics/4')
    fireEvent.change(screen.getByLabelText('Tên đề tài'), { target: { value: 'Unsaved proposal' } })
    expect(screen.getByRole('button', { name: 'Công bố' }).hasAttribute('disabled')).toBe(true)
    expect(screen.getByText(/Có chỉnh sửa chưa lưu/)).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Công bố' }))
    expect(current.publish).not.toHaveBeenCalled()
    expect(screen.queryByRole('dialog')).toBeNull()
  })
  it('renders loading, empty and forbidden states', () => {
    hook.useTopics.mockReturnValue(state({ loading: true })); const result = page(); expect(screen.getByText(/Đang tải danh mục/)).toBeTruthy(); result.unmount()
    hook.useTopics.mockReturnValue(state({ items: [] })); page(); expect(screen.getByText(/Không có đề tài/)).toBeTruthy(); cleanup()
    hook.useTopics.mockReturnValue(state({ isForbidden: true })); page(); expect(screen.getByText(/không có quyền quản lý/)).toBeTruthy()
  })
})
