import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { TopicManagementPage } from './TopicManagementPage'
const hook = vi.hoisted(() => ({ useTopics: vi.fn() }))
vi.mock('../hooks/useTopics', () => hook)
afterEach(cleanup)
const topic = { id: 4, code: 'AI-4', status: 'DRAFT' as const, projectPeriodId: 1, academicSemesterId: 1, leadDepartmentId: 2, leadDepartmentName: 'Computer Science', title: 'AI Assist', description: 'Description', problemStatement: null, objectives: null, expectedOutput: null, domain: null, technologies: [], keywords: [], projectMode: 'SINGLE_MAJOR' as const, primaryMajorId: 3, requirements: [{ majorId: 3, majorName: 'Software Engineering', minMembers: 1, maxMembers: 1, responsibility: 'Lead' }], concurrencyToken: 'token', closeReason: null }
const state = (overrides = {}) => ({ items: [topic], page: 1, pageSize: 20, totalCount: 1, current: null, filters: { status: 'DRAFT' as const, page: 1, pageSize: 20 }, setFilters: vi.fn(), loading: false, error: null, saving: false, refresh: vi.fn(), create: vi.fn().mockResolvedValue(topic), update: vi.fn().mockResolvedValue(topic), publish: vi.fn().mockResolvedValue(topic), close: vi.fn().mockResolvedValue(topic), isUnauthorized: false, isForbidden: false, ...overrides })
function page(path = '/department/topics') { return render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/department/topics" element={<TopicManagementPage />} /><Route path="/department/topics/:id" element={<TopicManagementPage />} /></Routes></MemoryRouter>) }
beforeEach(() => hook.useTopics.mockReturnValue(state()))
describe('TopicManagementPage', () => { it('renders ProjectTopic directory and real filters', () => { const current = state(); hook.useTopics.mockReturnValue(current); page(); expect(screen.getByText('AI Assist')).toBeTruthy(); expect(screen.getByText(/Computer Science/)).toBeTruthy(); fireEvent.change(screen.getByPlaceholderText('Search topics'), { target: { value: 'AI' } }); fireEvent.change(screen.getByLabelText('Topic status'), { target: { value: 'PUBLISHED' } }); expect(current.setFilters).toHaveBeenCalledWith(expect.objectContaining({ search: 'AI', page: 1 })); expect(current.setFilters).toHaveBeenLastCalledWith(expect.objectContaining({ status: 'PUBLISHED' })) }); it('covers detail, publish, update, and close interactions', () => { const current = state({ current: topic }); hook.useTopics.mockReturnValue(current); page('/department/topics/4'); expect(screen.getByText('Software Engineering: 1–1 · Lead')).toBeTruthy(); fireEvent.change(screen.getByLabelText('Edit title'), { target: { value: 'Edited' } }); fireEvent.click(screen.getByText('Save draft')); expect(current.update).toHaveBeenCalledWith(expect.objectContaining({ title: 'Edited' })); fireEvent.click(screen.getByText('Publish')); expect(current.publish).toHaveBeenCalledOnce(); fireEvent.change(screen.getByLabelText('Close reason'), { target: { value: 'Finished' } }); fireEvent.click(screen.getByText('Close')); expect(current.close).toHaveBeenCalledWith('Finished') }); it('renders loading, empty, 401, and 403 states', () => { hook.useTopics.mockReturnValue(state({ loading: true })); const result = page(); expect(screen.getByText(/Đang tải/)).toBeTruthy(); result.unmount(); hook.useTopics.mockReturnValue(state({ items: [] })); page(); expect(screen.getByText(/Không có topic/)).toBeTruthy(); cleanup(); hook.useTopics.mockReturnValue(state({ isUnauthorized: true })); page(); expect(screen.getByText('Đăng nhập')).toBeTruthy(); cleanup(); hook.useTopics.mockReturnValue(state({ isForbidden: true })); page(); expect(screen.getByText(/Department scope/)).toBeTruthy() }) })
