import { useState, type FormEvent, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { Button } from '../../../components/ui/Button'
import { HttpError } from '../../../services/http/http-client'
import { useAcademicGovernance } from '../hooks/useAcademicGovernance'
import { projectPeriodTypes, type GovernanceStatus, type ProjectPeriod, type ProjectPeriodDraft, type Semester, type SemesterDraft } from '../types/governance.types'
import './academic-governance.css'

const nextStates: Record<GovernanceStatus, GovernanceStatus[]> = { DRAFT: ['UPCOMING', 'ARCHIVED'], UPCOMING: ['ACTIVE', 'DRAFT'], ACTIVE: ['CLOSED'], CLOSED: ['ARCHIVED'], ARCHIVED: [] }
const labels: Record<string, string> = { REGISTRATION: 'Đăng ký', PROJECT_REVIEW: 'Xét duyệt', SUPERVISOR_SELECTION: 'Chọn GVHD', EXECUTION: 'Thực hiện', FINAL_SUBMISSION: 'Nộp cuối kỳ', EVALUATION: 'Đánh giá' }
type Editor = { kind: 'semester'; record?: Semester } | { kind: 'period'; record?: ProjectPeriod }

function errorText(error: Error) { return error instanceof HttpError && error.status === 403 ? 'Backend từ chối quyền quản trị cấu hình này.' : 'Không thể đồng bộ cấu hình học vụ. Hãy thử lại.' }
function toDate(value: string) { return value.slice(0, 10) }
function toDateTime(value: string) { return value.slice(0, 16) }

export function AcademicGovernancePage() {
  const [search, setSearch] = useState('')
  const [filters, setFilters] = useState({ search: '' })
  const [editor, setEditor] = useState<Editor | null>(null)
  const [operationError, setOperationError] = useState<string | null>(null)
  const [operationSuccess, setOperationSuccess] = useState<string | null>(null)
  const governance = useAcademicGovernance(filters)
  const openEditor = (next: Editor) => { setOperationError(null); setOperationSuccess(null); setEditor(next) }
  const saveSemester = async (draft: SemesterDraft) => { setOperationError(null); setOperationSuccess(null); try { await governance.saveSemester(draft); setEditor(null); setOperationSuccess('Đã lưu Semester. Danh sách đang được đồng bộ lại từ backend.') } catch (reason: unknown) { setOperationError(errorText(reason instanceof Error ? reason : new Error('Save failed'))) } }
  const savePeriod = async (draft: ProjectPeriodDraft) => { setOperationError(null); setOperationSuccess(null); try { await governance.saveProjectPeriod(draft); setEditor(null); setOperationSuccess('Đã lưu Project Period, Window và policy. Danh sách đang được đồng bộ lại từ backend.') } catch (reason: unknown) { setOperationError(errorText(reason instanceof Error ? reason : new Error('Save failed'))) } }
  const changeStatus = async (kind: 'semester' | 'period', id: number, status: GovernanceStatus, expectedStatus: GovernanceStatus) => { setOperationError(null); setOperationSuccess(null); try { await governance.setStatus(kind, id, status, expectedStatus); setOperationSuccess(`Đã yêu cầu chuyển trạng thái sang ${status}.`) } catch (reason: unknown) { setOperationError(errorText(reason instanceof Error ? reason : new Error('Status change failed'))) } }

  if (governance.isUnauthorized) return <section className="governance-state" role="alert"><strong>Cần đăng nhập để xem cấu hình học vụ.</strong><Link to="/login">Đăng nhập</Link></section>
  if (governance.loading) return <section className="governance-state" role="status">Đang tải Semester và Project Period…</section>
  if (governance.isForbidden) return <section className="governance-state" role="alert">Backend từ chối quyền truy cập Academic Governance.</section>
  if (governance.error) return <section className="governance-state" role="alert">{errorText(governance.error)} <Button onClick={governance.retry}>Thử lại</Button></section>
  return <div className="governance-page">
    <header><div><p className="eyebrow">UC-024 → UC-029</p><h1>Academic Governance</h1><p>Semester sở hữu các Project Period; mỗi Period hiện phản ánh contract Window/Policy do backend cung cấp; FE không tự suy diễn quyền hoặc trạng thái.</p><p className="mt-2 text-xs text-slate-500">Period policy governs windows, team-size and capacity. Project-specific mode, lead department and MajorRequirements remain on the Team/Project academic scope; they are never edited here.</p></div>{governance.canManage ? <div className="governance-actions"><Button onClick={() => openEditor({ kind: 'semester' })}>Thêm Semester</Button><Button variant="secondary" onClick={() => openEditor({ kind: 'period' })}>Thêm Project Period</Button></div> : null}</header>
    <form className="governance-filter" onSubmit={(event) => { event.preventDefault(); setFilters({ search }) }}><input aria-label="Tìm Semester hoặc Period" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm theo mã hoặc tên"/><Button type="submit" variant="secondary">Lọc</Button></form>
    {!governance.canManage ? <p className="governance-note">Chế độ xem: management actions chỉ xuất hiện khi backend workflow context cho phép.</p> : null}{operationError ? <p className="governance-error" role="alert">{operationError}</p> : null}{operationSuccess ? <p className="governance-message" role="status">{operationSuccess}</p> : null}
    <section><div className="governance-section-title"><h2>Academic Semester</h2><span>{governance.semesters.length} bản ghi</span></div><div className="governance-grid">{governance.semesters.map((semester) => <article key={semester.id} className="governance-card"><b>{semester.code}</b><h3>{semester.name}</h3><p>{semester.organizationCode} · {semester.startDate} → {semester.endDate}</p>{governance.canManage && !['CLOSED', 'ARCHIVED'].includes(semester.status) ? <Button size="sm" variant="secondary" onClick={() => openEditor({ kind: 'semester', record: semester })}>Chỉnh sửa</Button> : null}<Status status={semester.status} canManage={governance.canManage} onChange={(status) => changeStatus('semester', semester.id, status, semester.status)}/></article>)}</div>{governance.semesters.length === 0 ? <p className="governance-empty">Chưa có Semester phù hợp.</p> : null}</section>
    <section><div className="governance-section-title"><h2>Project Period Windows &amp; Policy</h2><span>{governance.periods.length} windows</span></div><div className="governance-periods">{governance.periods.map((period) => <article key={period.id} className="governance-period"><div><b>{labels[period.periodType]}</b><h3>{period.name}</h3><p>{period.semesterCode} · {period.startAt} → {period.endAt}</p></div>{governance.canManage && !['CLOSED', 'ARCHIVED'].includes(period.status) ? <Button size="sm" variant="secondary" onClick={() => openEditor({ kind: 'period', record: period })}>Chỉnh sửa</Button> : null}<Status status={period.status} canManage={governance.canManage} onChange={(status) => changeStatus('period', period.id, status, period.status)}/><dl><div><dt>Team size</dt><dd>{period.minTeamSize}–{period.maxTeamSize}</dd></div><div><dt>Distinct majors</dt><dd>{period.minDistinctMajors}</dd></div><div><dt>Supervisor capacity</dt><dd>{period.maxProjectsPerSupervisor}</dd></div></dl></article>)}</div>{governance.periods.length === 0 ? <p className="governance-empty">Chưa có Project Period/Window cho bộ lọc này.</p> : null}</section>
    {editor?.kind === 'semester' ? <SemesterForm record={editor.record} submitting={governance.submitting} onCancel={() => setEditor(null)} onSubmit={saveSemester}/> : null}{editor?.kind === 'period' ? <ProjectPeriodForm record={editor.record} semesters={governance.semesters} submitting={governance.submitting} onCancel={() => setEditor(null)} onSubmit={savePeriod}/> : null}
  </div>
}

function Status({ status, canManage, onChange }: { status: GovernanceStatus; canManage: boolean; onChange: (status: GovernanceStatus) => Promise<void> }) { return <div className="governance-status"><span>{status}</span>{canManage ? nextStates[status].map((next) => <Button key={next} size="sm" variant="outline" onClick={() => void onChange(next)}>{next}</Button>) : null}</div> }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="governance-modal" role="presentation"><section role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><Button variant="ghost" onClick={onClose}>Đóng</Button></header>{children}</section></div> }
function SemesterForm({ record, submitting, onCancel, onSubmit }: { record?: Semester; submitting: boolean; onCancel: () => void; onSubmit: (draft: SemesterDraft) => Promise<void> }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const startDate = String(form.get('startDate')); const endDate = String(form.get('endDate')); if (startDate > endDate) return; void onSubmit({ id: record?.id, organizationId: record?.organizationId ?? Number(form.get('organizationId')), code: String(form.get('code')), name: String(form.get('name')), startDate, endDate }) }; return <Modal title={record ? 'Chỉnh sửa Semester' : 'Tạo Semester'} onClose={onCancel}><form onSubmit={submit}>{!record ? <label>Organization ID<input name="organizationId" type="number" min="1" required/></label> : null}<label>Mã Semester<input name="code" required defaultValue={record?.code}/></label><label>Tên Semester<input name="name" required defaultValue={record?.name}/></label><label>Bắt đầu<input name="startDate" type="date" required defaultValue={record ? toDate(record.startDate) : undefined}/></label><label>Kết thúc<input name="endDate" type="date" required defaultValue={record ? toDate(record.endDate) : undefined}/></label><Button type="submit" disabled={submitting}>{record ? 'Lưu thay đổi' : 'Lưu Semester'}</Button></form></Modal> }
function ProjectPeriodForm({ record, semesters, submitting, onCancel, onSubmit }: { record?: ProjectPeriod; semesters: Semester[]; submitting: boolean; onCancel: () => void; onSubmit: (draft: ProjectPeriodDraft) => Promise<void> }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const startAt = String(form.get('startAt')); const endAt = String(form.get('endAt')); const minTeamSize = Number(form.get('minTeamSize')); const maxTeamSize = Number(form.get('maxTeamSize')); const minDistinctMajors = Number(form.get('minDistinctMajors')); if (startAt >= endAt || maxTeamSize < minTeamSize || minDistinctMajors > maxTeamSize) return; void onSubmit({ id: record?.id, academicSemesterId: record?.academicSemesterId ?? Number(form.get('semesterId')), code: String(form.get('code')), name: String(form.get('name')), periodType: String(form.get('periodType')) as ProjectPeriodDraft['periodType'], startAt, endAt, minTeamSize, maxTeamSize, minDistinctMajors, maxProjectsPerSupervisor: Number(form.get('maxProjectsPerSupervisor')), rubricId: record?.rubricId ?? null }) }; return <Modal title={record ? 'Chỉnh sửa Project Period / Window' : 'Tạo Project Period / Window'} onClose={onCancel}><form onSubmit={submit}>{!record ? <label>Semester<select name="semesterId" required defaultValue=""><option value="" disabled>Chọn Semester</option>{semesters.map((semester) => <option key={semester.id} value={semester.id}>{semester.code} · {semester.name}</option>)}</select></label> : null}<label>Mã Period<input name="code" required defaultValue={record?.code}/></label><label>Tên Period<input name="name" required defaultValue={record?.name}/></label><label>Loại Window<select name="periodType" defaultValue={record?.periodType}>{projectPeriodTypes.map((type) => <option key={type} value={type}>{labels[type]}</option>)}</select></label><label>Bắt đầu<input name="startAt" type="datetime-local" required defaultValue={record ? toDateTime(record.startAt) : undefined}/></label><label>Kết thúc<input name="endAt" type="datetime-local" required defaultValue={record ? toDateTime(record.endAt) : undefined}/></label><label>Team size tối thiểu<input name="minTeamSize" type="number" min="1" required defaultValue={record?.minTeamSize ?? 3}/></label><label>Team size tối đa<input name="maxTeamSize" type="number" min="1" required defaultValue={record?.maxTeamSize ?? 5}/></label><label>Distinct majors tối thiểu<input name="minDistinctMajors" type="number" min="1" required defaultValue={record?.minDistinctMajors ?? 1}/></label><label>Supervisor capacity<input name="maxProjectsPerSupervisor" type="number" min="1" required defaultValue={record?.maxProjectsPerSupervisor ?? 5}/></label><Button type="submit" disabled={submitting}>{record ? 'Lưu thay đổi' : 'Lưu Window & Policy'}</Button></form></Modal> }
