import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { Button } from '../../../components/ui/Button'
import { HttpError } from '../../../services/http/http-client'
import type { Permission, Role, SecurityCatalogDraft, UserAccount, UserDraft } from '../api/admin-api'
import { useAdminWorkspace } from '../hooks/useAdminWorkspace'
import './admin-security.css'

const blankUser: UserDraft = { departmentId: null, majorId: null, email: '', password: '', fullName: '', phone: null, studentCode: null, employeeCode: null, title: null, roleIds: [] }
const errorDetail = (error: unknown) => error instanceof HttpError ? error.message : 'Backend không thể hoàn tất thao tác.'
const draftFrom = (form: HTMLFormElement): SecurityCatalogDraft => { const data = new FormData(form); return { code: String(data.get('code') ?? '').trim(), name: String(data.get('name') ?? '').trim(), description: String(data.get('description') ?? '').trim() || null } }

export function AdminSecurityPage() {
  const admin = useAdminWorkspace()
  const [message, setMessage] = useState<string | null>(null)
  const [importText, setImportText] = useState('')
  const run = async (action: () => Promise<unknown>, success: string) => { try { await action(); setMessage(success) } catch (error) { setMessage(errorDetail(error)) } }
  if (admin.isUnauthorized) return <section className="admin-state"><Link to="/login">Đăng nhập để quản trị tài khoản</Link></section>
  if (admin.loading) return <section className="admin-state" aria-live="polite">Đang tải User, Role, Permission và Audit…</section>
  if (admin.isForbidden) return <section className="admin-state">Backend từ chối quyền Account Security Management.</section>
  if (admin.error) return <section className="admin-state">{errorDetail(admin.error)} <Button onClick={admin.refresh}>Thử lại</Button></section>
  const createUser = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const id = (key: string) => { const value = Number(form.get(key)); return value > 0 ? value : null }
    await run(() => admin.createUser({ ...blankUser, email: String(form.get('email') ?? '').trim(), password: String(form.get('password') ?? ''), fullName: String(form.get('fullName') ?? '').trim(), departmentId: id('departmentId'), majorId: id('majorId'), roleIds: String(form.get('roleIds') ?? '').split(',').map(Number).filter(Boolean) }), 'Đã gửi tạo tài khoản tới backend.')
  }
  return <main className="admin-page" aria-labelledby="admin-security-title">
    <header><p className="eyebrow">G4 · G5</p><h1 id="admin-security-title">User, Access &amp; Audit</h1><p>Quyền, scope và catalog được backend xác thực. Role hệ thống chỉ hiển thị để tránh ghi đè chính sách nền tảng.</p></header>
    {message ? <p className="admin-message" role="status">{message}</p> : null}
    <section aria-labelledby="admin-users-title"><h2 id="admin-users-title">Users</h2><form className="admin-create" onSubmit={createUser}>
      <input name="fullName" required placeholder="Họ tên" aria-label="Họ tên" /><input name="email" type="email" required placeholder="Email" aria-label="Email" /><input name="password" type="password" required placeholder="Mật khẩu mạnh" aria-label="Mật khẩu" /><input name="roleIds" required placeholder="Role IDs, ví dụ: 1,2" aria-label="Role IDs" /><input name="departmentId" type="number" min="1" placeholder="Verified Department ID" aria-label="Department ID" /><input name="majorId" type="number" min="1" placeholder="Verified Major ID" aria-label="Major ID" /><Button type="submit">Tạo account</Button>
    </form><p>Academic scope chỉ nhận ID đã được xác thực từ Academic Structure; không có chọn Major tự khai báo.</p><div className="admin-list">{admin.users.map(user => <UserRow key={user.id} user={user} roles={admin.roles} onStatus={status => run(() => admin.setStatus(user.id, status), 'Đã gửi thay đổi trạng thái.')} onAssign={roleId => run(() => admin.assignRole(user.id, roleId), 'Đã gửi gán role.')} onRemove={roleId => run(() => admin.removeRole(user.id, roleId), 'Đã gửi gỡ role.')} />)}</div>{admin.users.length === 0 ? <p>Không có user phù hợp.</p> : null}</section>
    <section aria-labelledby="admin-roles-title"><h2 id="admin-roles-title">Role catalogue</h2><CatalogCreateForm noun="role" onCreate={draft => run(() => admin.createRole(draft), 'Đã tạo role qua backend.')} /><div className="admin-list">{admin.roles.map(role => <RoleRow key={role.id} role={role} permissions={admin.permissions} onSave={draft => run(() => admin.updateRole(role.id, draft), 'Đã cập nhật role qua backend.')} onDelete={() => run(() => admin.deleteRole(role.id), 'Đã xóa role qua backend.')} onPermissions={ids => run(() => admin.replacePermissions(role.id, ids), 'Đã cập nhật mapping role-permission.')} />)}</div>{admin.roles.length === 0 ? <p>Không có role trong catalog.</p> : null}</section>
    <section aria-labelledby="admin-permissions-title"><h2 id="admin-permissions-title">Permission catalogue</h2><CatalogCreateForm noun="permission" onCreate={draft => run(() => admin.createPermission(draft), 'Đã tạo permission qua backend.')} /><div className="admin-list">{admin.permissions.map(permission => <PermissionRow key={permission.id} permission={permission} onSave={draft => run(() => admin.updatePermission(permission.id, draft), 'Đã cập nhật permission qua backend.')} onDelete={() => run(() => admin.deletePermission(permission.id), 'Đã xóa permission qua backend.')} />)}</div>{admin.permissions.length === 0 ? <p>Không có permission trong catalog.</p> : null}</section>
    <section aria-labelledby="admin-matrix-title"><h2 id="admin-matrix-title">Permission matrix</h2>{admin.matrix ? <PermissionMatrix roles={admin.matrix.roles} permissions={admin.matrix.permissions} /> : <p>Backend chưa trả về permission matrix.</p>}</section>
    <section aria-labelledby="admin-import-title"><h2 id="admin-import-title">Account import — JSON contract</h2><p>Backend không hỗ trợ upload CSV/Excel, preview hay partial result. Gửi 1–500 account JSON theo schema create-account; backend xử lý toàn-batch.</p><textarea value={importText} onChange={event => setImportText(event.target.value)} aria-label="Account import JSON" placeholder={'[{"email":"...","password":"...","fullName":"...","roleIds":[1],"departmentId":null,"majorId":null,"phone":null,"studentCode":null,"employeeCode":null,"title":null}]'} /><Button disabled={!importText.trim()} onClick={() => { try { const accounts = JSON.parse(importText) as UserDraft[]; void run(() => admin.importUsers(accounts), 'Backend đã nhập batch thành công.') } catch { setMessage('JSON import không hợp lệ.') } }}>Nhập JSON</Button></section>
    <section aria-labelledby="admin-audit-title"><h2 id="admin-audit-title">Audit log</h2><div className="admin-list">{admin.audit.map(record => <article key={record.id}><b>{record.action}</b><p>{record.entityType} #{record.entityId ?? '—'} · {record.outcome} · {record.occurredAt}</p></article>)}</div>{admin.audit.length === 0 ? <p>Không có audit record.</p> : null}</section>
  </main>
}

function UserRow({ user, roles, onStatus, onAssign, onRemove }: { user: UserAccount; roles: Pick<Role, 'id' | 'code'>[]; onStatus: (status: UserAccount['status']) => Promise<void>; onAssign: (roleId: number) => Promise<void>; onRemove: (roleId: number) => Promise<void> }) { return <article><details><summary><b>{user.fullName}</b> · {user.email} · {user.status}</summary><p>Department {user.departmentId ?? '—'} · Major {user.majorId ?? '—'} · Failed access {user.accessFailedCount}</p><p>{user.roles.join(', ') || 'Chưa có role'}</p></details><div className="admin-actions">{user.status !== 'ACTIVE' ? <Button size="sm" onClick={() => void onStatus('ACTIVE')}>Activate</Button> : null}{user.status !== 'INACTIVE' ? <Button size="sm" variant="secondary" onClick={() => void onStatus('INACTIVE')}>Deactivate</Button> : null}{user.status !== 'SUSPENDED' ? <Button size="sm" variant="outline" onClick={() => void onStatus('SUSPENDED')}>Lock</Button> : null}</div><select aria-label={`Assign role for ${user.fullName}`} defaultValue="" onChange={event => event.target.value && void onAssign(Number(event.target.value))}><option value="">Gán role…</option>{roles.map(role => <option key={role.id} value={role.id}>{role.code}</option>)}</select><div className="admin-actions">{roles.filter(role => user.roles.includes(role.code)).map(role => <Button key={role.id} size="sm" variant="ghost" onClick={() => void onRemove(role.id)}>Gỡ {role.code}</Button>)}</div></article> }

function CatalogCreateForm({ noun, onCreate }: { noun: 'role' | 'permission'; onCreate: (draft: SecurityCatalogDraft) => Promise<void> }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void onCreate(draftFrom(event.currentTarget)).then(() => event.currentTarget.reset()) }; return <form className="admin-catalog-form" onSubmit={submit}><input name="code" required maxLength={noun === 'role' ? 50 : 100} placeholder={`${noun} code`} aria-label={`New ${noun} code`} /><input name="name" required maxLength={150} placeholder="Tên hiển thị" aria-label={`New ${noun} name`} /><input name="description" maxLength={500} placeholder="Mô tả (không bắt buộc)" aria-label={`New ${noun} description`} /><Button type="submit">Tạo {noun}</Button></form> }

function RoleRow({ role, permissions, onSave, onDelete, onPermissions }: { role: Role; permissions: Permission[]; onSave: (draft: SecurityCatalogDraft) => Promise<void>; onDelete: () => Promise<void>; onPermissions: (ids: number[]) => Promise<void> }) { const [editing, setEditing] = useState(false); return <article><div className="admin-row-heading"><b>{role.code}</b>{role.isSystemRole ? <span className="admin-system">System role</span> : null}</div><p>{role.name} · {role.description || 'Không có mô tả'}</p><p>Permissions: {role.permissions.map(permission => permission.code).join(', ') || 'Chưa có permission'}</p>{editing ? <form className="admin-catalog-form" onSubmit={event => { event.preventDefault(); void onSave(draftFrom(event.currentTarget)).then(() => setEditing(false)) }}><input name="code" defaultValue={role.code} required maxLength={50} aria-label={`Role ${role.id} code`} /><input name="name" defaultValue={role.name} required maxLength={150} aria-label={`Role ${role.id} name`} /><input name="description" defaultValue={role.description ?? ''} maxLength={500} aria-label={`Role ${role.id} description`} /><Button type="submit">Lưu</Button><Button type="button" variant="secondary" onClick={() => setEditing(false)}>Hủy</Button></form> : null}<label>Permission IDs (thay thế toàn bộ)<input defaultValue={role.permissions.map(permission => permission.id).join(',')} onBlur={event => { const ids = event.currentTarget.value.split(',').map(Number).filter(Boolean); if (ids.length !== role.permissions.length || ids.some(id => !role.permissions.some(permission => permission.id === id))) void onPermissions(ids) }} /></label><div className="admin-actions"><Button size="sm" variant="secondary" onClick={() => setEditing(true)} disabled={role.isSystemRole}>Sửa role</Button><Button size="sm" variant="outline" disabled={role.isSystemRole} onClick={() => { if (window.confirm(`Xóa role ${role.code}?`)) void onDelete() }}>Xóa role</Button></div><p className="admin-contract-note">Catalog permissions có {permissions.length} mục được backend cung cấp.</p></article> }

function PermissionRow({ permission, onSave, onDelete }: { permission: Permission; onSave: (draft: SecurityCatalogDraft) => Promise<void>; onDelete: () => Promise<void> }) { const [editing, setEditing] = useState(false); return <article><div className="admin-row-heading"><b>{permission.code}</b>{permission.isSystemPermission ? <span className="admin-system">System permission</span> : null}</div><p>{permission.name} · {permission.description || 'Không có mô tả'}</p>{editing ? <form className="admin-catalog-form" onSubmit={event => { event.preventDefault(); void onSave(draftFrom(event.currentTarget)).then(() => setEditing(false)) }}><input name="code" defaultValue={permission.code} required maxLength={100} aria-label={`Permission ${permission.id} code`} /><input name="name" defaultValue={permission.name} required maxLength={150} aria-label={`Permission ${permission.id} name`} /><input name="description" defaultValue={permission.description ?? ''} maxLength={500} aria-label={`Permission ${permission.id} description`} /><Button type="submit">Lưu</Button><Button type="button" variant="secondary" onClick={() => setEditing(false)}>Hủy</Button></form> : null}<div className="admin-actions"><Button size="sm" variant="secondary" disabled={permission.isSystemPermission} onClick={() => setEditing(true)}>Sửa permission</Button><Button size="sm" variant="outline" disabled={permission.isSystemPermission} onClick={() => { if (window.confirm(`Xóa permission ${permission.code}?`)) void onDelete() }}>Xóa permission</Button></div></article> }

function PermissionMatrix({ roles, permissions }: { roles: Role[]; permissions: Permission[] }) { return <div className="admin-matrix-scroll" tabIndex={0} aria-label="Permission matrix, cuộn ngang khi cần"><table className="admin-matrix"><thead><tr><th scope="col">Permission</th>{roles.map(role => <th scope="col" key={role.id}>{role.code}</th>)}</tr></thead><tbody>{permissions.map(permission => <tr key={permission.id}><th scope="row">{permission.code}</th>{roles.map(role => <td key={role.id}>{role.permissions.some(assigned => assigned.id === permission.id) ? '✓' : '—'}</td>)}</tr>)}</tbody></table></div> }
