import { useState, type FormEvent } from 'react'
import type { BackendTaskStatus } from '../../types/backend'
import '../tasks/pages/task-board.css'
import { BoardFixture } from './BoardFixture'
import { MeetingCalendar } from './MeetingCalendar'
import { ChatPreview } from './ChatPreview'
import type { Recurrence } from './meeting-calendar'

type FixtureTask = { id: number; title: string; status: BackendTaskStatus; assignee: string; due: string; sprint: number | null; comments: string[]; subtasks: { title: string; done: boolean }[]; activity: string[] }
type FixtureSprint = { id: number; name: string; goal: string; start: string; end: string; status: 'PLANNING' | 'ACTIVE' | 'COMPLETED' }
type FixtureMeeting = { id: number; title: string; start: string; end: string; link: string; notes: string; locked: boolean; cancelled: boolean; decisions: string[]; attendees: string[]; responses: Record<string, string>; recurrence: Recurrence; until: string; reminder: string }
const statuses: BackendTaskStatus[] = ['TODO', 'IN_PROGRESS', 'BLOCKED', 'IN_REVIEW', 'DONE', 'CANCELLED']
const people = ['Nguyễn An', 'Trần Bình', 'Supervisor fixture']
const seedTasks: FixtureTask[] = [
  { id: 1, title: 'Đối chiếu contract COLD', status: 'TODO', assignee: people[0], due: '2026-10-15', sprint: null, comments: [], subtasks: [{ title: 'Danh mục report', done: false }], activity: ['Tạo task fixture'] },
  { id: 2, title: 'Kiểm thử điểm còn thiếu', status: 'IN_PROGRESS', assignee: people[1], due: '2026-10-16', sprint: null, comments: [], subtasks: [], activity: ['Tạo task fixture'] },
]

/** Proposed UX for resources without stable contracts. All state dies on reload. */
export function CollaborationPreview() {
  const [section, setSection] = useState<'tasks' | 'sprints' | 'meetings' | 'chat'>('tasks')
  const [tasks, setTasks] = useState<FixtureTask[]>(seedTasks)
  const [sprints, setSprints] = useState<FixtureSprint[]>([])
  const [meetings, setMeetings] = useState<FixtureMeeting[]>([])
  const [view, setView] = useState<'board' | 'list' | 'timeline'>('board')
  const [meetingView, setMeetingView] = useState<'list' | 'calendar'>('list')
  const [wip, setWip] = useState(0)
  const [filter, setFilter] = useState('')
  const [selected, setSelected] = useState<number | null>(null)
  const [taskTitle, setTaskTitle] = useState('')
  const [comment, setComment] = useState('')
  const [subtask, setSubtask] = useState('')
  const [message, setMessage] = useState('')
  const [sprintForm, setSprintForm] = useState({ name: '', goal: '', start: '', end: '' })
  const [meetingForm, setMeetingForm] = useState({ title: '', start: '', end: '', link: '', recurrence: 'NONE' as Recurrence, until: '', reminder: '15' })
  const [attendees, setAttendees] = useState<string[]>([people[0], people[1]])
  const detail = tasks.find(item => item.id === selected)
  const filtered = tasks.filter(item => !filter || item.assignee === filter)
  const updateTask = (id: number, patch: Partial<FixtureTask>, activity: string) => setTasks(current => current.map(item => item.id === id ? { ...item, ...patch, activity: [...item.activity, activity] } : item))
  const createSprint = (event: FormEvent) => {
    event.preventDefault()
    if (!sprintForm.name.trim() || !sprintForm.start || !sprintForm.end || sprintForm.end < sprintForm.start) { setMessage('SPRINT_DATES_INVALID · Điền tên và ngày kết thúc không trước ngày bắt đầu.'); return }
    setSprints(current => [...current, { ...sprintForm, name: sprintForm.name.trim(), id: current.length + 1, status: 'PLANNING' }]); setSprintForm({ name: '', goal: '', start: '', end: '' }); setMessage('Đã tạo sprint fixture.')
  }
  const createMeeting = (event: FormEvent) => {
    event.preventDefault()
    if (!meetingForm.title.trim() || !meetingForm.start || !meetingForm.end || meetingForm.end <= meetingForm.start || !attendees.length) { setMessage('MEETING_INVALID · Điền tiêu đề, người tham dự và giờ kết thúc sau giờ bắt đầu.'); return }
    if (meetingForm.link && !/^https?:\/\//i.test(meetingForm.link)) { setMessage('MEETING_URL_INVALID · Link online phải dùng HTTP/HTTPS.'); return }
    if (meetingForm.recurrence !== 'NONE' && (!meetingForm.until || meetingForm.until < meetingForm.start.slice(0, 10))) { setMessage('RECURRENCE_UNTIL_INVALID · Chọn ngày kết thúc lặp không trước ngày bắt đầu.'); return }
    setMeetings(current => [...current, { ...meetingForm, id: current.length + 1, notes: '', locked: false, cancelled: false, decisions: [], attendees: [...attendees], responses: {} }]); setMessage('Đã tạo meeting fixture. Chưa gửi email/nhắc lịch; cần BE delivery contract.')
  }
  const updateMeeting = (id: number, patch: Partial<FixtureMeeting>) => setMeetings(current => current.map(item => item.id === id ? { ...item, ...patch } : item))
  return <section className="v5-card" aria-label="Collaboration fixture">
    <h2>Task, sprint và meeting — fixture riêng</h2><p>Không đồng nhất sprint với milestone thật. Chuyển trạng thái dưới đây chỉ thay đổi dữ liệu thử nghiệm.</p>
    <nav className="v5-nav" aria-label="Phân hệ collaboration">{([['tasks', 'Task'], ['sprints', 'Sprint'], ['meetings', 'Meeting'], ['chat', 'Chat']] as const).map(([key, label]) => <button type="button" key={key} aria-pressed={section === key} onClick={() => { setSection(key); setMessage('') }}>{label}</button>)}</nav>
    {message && <p role="status">{message}</p>}
    {section === 'tasks' && <>
      <div className="v5-controls"><label>Lọc người phụ trách<select value={filter} onChange={event => setFilter(event.target.value)}><option value="">Cả nhóm</option>{people.slice(0, 2).map(person => <option key={person}>{person}</option>)}</select></label>{(['board', 'list', 'timeline'] as const).map(value => <button type="button" key={value} aria-pressed={view === value} onClick={() => setView(value)}>{value === 'board' ? 'Board fixture' : value === 'list' ? 'List fixture' : 'Timeline fixture'}</button>)}{view === 'board' && <label>Giới hạn WIP mỗi cột (0 = tắt)<input type="number" min={0} max={9} value={wip} onChange={event => setWip(Math.max(0, Number(event.target.value) || 0))} /></label>}</div>
      <form className="v5-controls" onSubmit={event => { event.preventDefault(); if (!taskTitle.trim()) return; setTasks(current => [...current, { ...seedTasks[0], id: Math.max(...current.map(item => item.id), 0) + 1, title: taskTitle.trim(), subtasks: [], activity: ['Tạo task fixture'] }]); setTaskTitle('') }}><label>Tên task fixture<input value={taskTitle} maxLength={200} required onChange={event => setTaskTitle(event.target.value)} /></label><button type="submit">Tạo task fixture</button></form>
      {view === 'board' ? <BoardFixture cards={filtered.map(item => ({ id: item.id, status: item.status, title: item.title, assignee: item.assignee, due: item.due }))} statuses={statuses} wipLimit={wip} onSelect={setSelected} onMove={(id, status, note) => updateTask(id, { status: status as BackendTaskStatus }, note)} /> : view === 'list' ? <ul>{filtered.map(item => <li key={item.id}><button type="button" onClick={() => setSelected(item.id)}>#{item.id} · {item.title} · {item.status}</button></li>)}</ul> : <section aria-label="Timeline fixture"><p>Timeline theo hạn minh họa; chưa có contract dependencies/date mutation.</p>{filtered.map(item => <div key={item.id} className="v5-timeline"><button type="button" onClick={() => setSelected(item.id)}>{item.title}</button><time dateTime={item.due}>{item.due || 'Chưa có hạn'}</time></div>)}</section>}
      {!filtered.length && <p>Không có task theo bộ lọc.</p>}
      {detail && <section className="v5-card" aria-label="Chi tiết task fixture"><h3>Task #{detail.id}</h3><label>Tiêu đề task<input value={detail.title} onChange={event => updateTask(detail.id, { title: event.target.value }, 'Sửa tiêu đề')} /></label><div className="v5-controls"><label>Trạng thái task<select value={detail.status} onChange={event => updateTask(detail.id, { status: event.target.value as BackendTaskStatus }, 'Đổi trạng thái bằng bàn phím')}>{statuses.map(status => <option key={status}>{status}</option>)}</select></label><label>Người phụ trách task<select value={detail.assignee} onChange={event => updateTask(detail.id, { assignee: event.target.value }, 'Đổi người phụ trách')}>{people.slice(0, 2).map(person => <option key={person}>{person}</option>)}</select></label><label>Sprint của task<select value={detail.sprint ?? ''} onChange={event => updateTask(detail.id, { sprint: event.target.value ? Number(event.target.value) : null }, 'Đổi sprint fixture')}><option value="">Backlog</option>{sprints.filter(item => item.status !== 'COMPLETED' || item.id === detail.sprint).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Hạn task<input type="date" value={detail.due} onChange={event => updateTask(detail.id, { due: event.target.value }, 'Đổi hạn fixture')} /></label></div>
        <h3>Subtasks</h3>{detail.subtasks.map((item, index) => <label className="v5-check" key={index}><input type="checkbox" checked={item.done} onChange={event => updateTask(detail.id, { subtasks: detail.subtasks.map((sub, i) => i === index ? { ...sub, done: event.target.checked } : sub) }, 'Cập nhật subtask')} />{item.title}</label>)}<form onSubmit={event => { event.preventDefault(); if (!subtask.trim()) return; updateTask(detail.id, { subtasks: [...detail.subtasks, { title: subtask.trim(), done: false }] }, 'Thêm subtask'); setSubtask('') }}><label>Subtask mới<input value={subtask} onChange={event => setSubtask(event.target.value)} /></label><button type="submit">Thêm subtask</button></form>
        <h3>Bình luận</h3><ul>{detail.comments.map((value, index) => <li key={index}>{value}</li>)}</ul><form onSubmit={event => { event.preventDefault(); if (!comment.trim()) return; updateTask(detail.id, { comments: [...detail.comments, comment.trim()] }, 'Thêm bình luận'); setComment('') }}><label>Bình luận task<textarea value={comment} onChange={event => setComment(event.target.value)} /></label><button type="submit">Gửi bình luận fixture</button></form><h3>Activity fixture</h3><ul>{detail.activity.slice(-5).map((value, index) => <li key={index}>{value}</li>)}</ul><button type="button" onClick={() => setSelected(null)}>Đóng chi tiết task</button>
      </section>}
    </>}
    {section === 'sprints' && <><form onSubmit={createSprint}><div className="v5-controls">{(['name', 'goal', 'start', 'end'] as const).map(key => <label key={key}>{({ name: 'Tên sprint', goal: 'Mục tiêu sprint', start: 'Bắt đầu sprint', end: 'Kết thúc sprint' })[key]}<input type={key === 'start' || key === 'end' ? 'date' : 'text'} value={sprintForm[key]} onChange={event => setSprintForm({ ...sprintForm, [key]: event.target.value })} /></label>)}<button type="submit">Tạo sprint fixture</button></div></form>{sprints.map(item => { const assigned = tasks.filter(task => task.sprint === item.id); return <section key={item.id} className="v5-card"><h3>{item.name} · {item.status}</h3><p>{item.goal} · {item.start} — {item.end}</p><p>{assigned.filter(task => task.status === 'DONE').length}/{assigned.length} task DONE. Chưa có dữ liệu burndown theo ngày.</p>{item.status === 'PLANNING' && <button type="button" onClick={() => { if (sprints.some(sprint => sprint.status === 'ACTIVE')) { setMessage('ACTIVE_SPRINT_EXISTS · Fixture chỉ cho một sprint đang chạy.'); return } setSprints(current => current.map(sprint => sprint.id === item.id ? { ...sprint, status: 'ACTIVE' } : sprint)) }}>Bắt đầu {item.name}</button>}{item.status === 'ACTIVE' && <button type="button" onClick={() => { if (assigned.some(task => task.status !== 'DONE' && task.status !== 'CANCELLED')) { setMessage('SPRINT_TASKS_PENDING · Hoàn tất task hoặc chuyển về backlog trước khi đóng fixture.'); return } setSprints(current => current.map(sprint => sprint.id === item.id ? { ...sprint, status: 'COMPLETED' } : sprint)) }}>Hoàn tất {item.name}</button>}</section> })}<h3>Backlog</h3><ul>{tasks.filter(item => item.sprint === null).map(item => <li key={item.id}>{item.title}</li>)}</ul></>}
    {section === 'meetings' && <><form onSubmit={createMeeting}><div className="v5-controls">{(['title', 'start', 'end', 'link'] as const).map(key => <label key={key}>{({ title: 'Tiêu đề meeting', start: 'Bắt đầu meeting (giờ địa phương)', end: 'Kết thúc meeting (giờ địa phương)', link: 'Link online meeting' })[key]}<input type={key === 'start' || key === 'end' ? 'datetime-local' : key === 'link' ? 'url' : 'text'} value={meetingForm[key]} onChange={event => setMeetingForm({ ...meetingForm, [key]: event.target.value })} /></label>)}<label>Lặp lịch<select value={meetingForm.recurrence} onChange={event => setMeetingForm({ ...meetingForm, recurrence: event.target.value as Recurrence })}><option value="NONE">Không lặp</option><option value="WEEKLY">Hàng tuần</option><option value="BIWEEKLY">Hai tuần một lần</option></select></label>{meetingForm.recurrence !== 'NONE' && <label>Lặp đến ngày<input type="date" value={meetingForm.until} onChange={event => setMeetingForm({ ...meetingForm, until: event.target.value })} /></label>}<label>Nhắc trước (phút)<select value={meetingForm.reminder} onChange={event => setMeetingForm({ ...meetingForm, reminder: event.target.value })}>{['0', '15', '30', '60'].map(value => <option key={value} value={value}>{value === '0' ? 'Không nhắc' : `${value} phút`}</option>)}</select></label></div><fieldset><legend>Người tham dự fixture</legend>{people.map(person => <label key={person} className="v5-check"><input type="checkbox" checked={attendees.includes(person)} onChange={event => setAttendees(current => event.target.checked ? [...current, person] : current.filter(value => value !== person))} />{person}</label>)}</fieldset><button type="submit">Tạo meeting fixture</button></form>
      <div className="v5-controls" role="group" aria-label="Kiểu xem meeting">{(['list', 'calendar'] as const).map(value => <button type="button" key={value} aria-pressed={meetingView === value} onClick={() => setMeetingView(value)}>{value === 'list' ? 'Danh sách' : 'Lịch'}</button>)}</div>
      {meetingView === 'calendar' && <MeetingCalendar events={meetings.map(item => ({ id: item.id, title: item.title, start: item.start, end: item.end, recurrence: item.recurrence, until: item.until, cancelled: item.cancelled }))} onPickDay={iso => { setMeetingForm(current => ({ ...current, start: current.start || `${iso}T09:00`, end: current.end || `${iso}T10:00` })); setMessage(`Đã chọn ngày ${iso} vào form tạo meeting fixture.`) }} />}
      {meetingView === 'list' && !meetings.length && <p>Chưa có cuộc họp fixture.</p>}{meetingView === 'list' && meetings.map(item =><section key={item.id} className="v5-card"><h3>{item.title} · {item.cancelled ? 'CANCELLED' : 'SCHEDULED'}</h3><p>{item.start.replace('T', ' ')} — {item.end.replace('T', ' ')}</p><p>{item.recurrence === 'NONE' ? 'Không lặp' : item.recurrence === 'WEEKLY' ? `Lặp hàng tuần đến ${item.until}` : `Lặp hai tuần/lần đến ${item.until}`} · Nhắc trước {item.reminder === '0' ? 'tắt' : `${item.reminder} phút`}</p><p>Email/nhắc lịch: chưa có BE delivery; không gửi từ fixture.</p>{item.attendees.map(person => <label key={person}>RSVP {person}<select value={item.responses[person] ?? 'PENDING'} disabled={item.cancelled} onChange={event => updateMeeting(item.id, { responses: { ...item.responses, [person]: event.target.value } })}>{['PENDING', 'ACCEPTED', 'DECLINED', 'TENTATIVE'].map(value => <option key={value}>{value}</option>)}</select></label>)}<label>Biên bản {item.title}<textarea value={item.notes} disabled={item.locked || item.cancelled} onChange={event => updateMeeting(item.id, { notes: event.target.value })} /></label><p>{item.locked ? 'LOCKED — chỉ xem' : 'Tự lưu trong bộ nhớ phiên fixture'}</p><button type="button" disabled={item.locked || item.cancelled || !item.notes.trim()} onClick={() => updateMeeting(item.id, { locked: true })}>Khóa biên bản {item.title}</button><button type="button" disabled={item.cancelled || item.locked} onClick={() => updateMeeting(item.id, { cancelled: true })}>Hủy meeting {item.title}</button></section>)}</>}
    {section === 'chat' && <ChatPreview />}
  </section>
}
